# Generated by Django 3.2.7 on 2021-11-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True)),
                ('type', models.TextField(choices=[('Password', 'Password'), ('Endpoint', 'Endpoint')], max_length=10)),
                ('path', models.TextField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
