# Generated by Django 3.2.16 on 2023-01-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='type',
            field=models.TextField(choices=[('Endpoint', 'Endpoint'), ('Subdomain', 'Subdomain')], max_length=10),
        ),
    ]
