# Generated by Django 3.2.16 on 2022-12-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='type',
            field=models.TextField(choices=[('Endpoint', 'Endpoint')], max_length=10),
        ),
    ]
