# Generated by Django 5.2.16 on 2026-08-10 09:25
# Touched: the TargetDenylist table is initialized with the default denied targets

from typing import Any

import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models

DEFAULT_TARGETS = [
    "127.0.0.1", "::1", "localhost", "frontend", "backend", "postgres", "valkey", "initializer",
    "tasks-worker", "executions-worker", "findings-worker", "telegram-bot", "nginx"
]


def create_default_target_denylist(apps: Any, schema_editor: Any) -> None:
    """Create the denylist entries that keep Rekono from scanning its own deployment.

    Every entry is new, since the table is created by this same migration, so none of them
    has blocked any target yet.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is created.
    """
    model = apps.get_model("target_denylist", "TargetDenylist")
    for target in DEFAULT_TARGETS:
        model.objects.get_or_create(target=target, defaults={"default": True})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetDenylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(max_length=100, unique=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('default', models.BooleanField(default=False)),
                ('blocked', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.RunPython(create_default_target_denylist, migrations.RunPython.noop),
    ]
