# Generated by Django 5.2.16 on 2026-08-10 09:25

import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetDenylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(max_length=100, unique=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('default', models.BooleanField(default=False)),
                ('blocked', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
    ]
