# Generated by Django 5.2.16 on 2026-08-10 09:25

import django.db.models.deletion
import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_remove_project_defectdojo_engagement_by_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(choices=[('OSINT', 'Osint'), ('Host', 'Host'), ('Open Port', 'Open Port'), ('Service', 'Service'), ('Technology', 'Technology'), ('Credential', 'Credential'), ('Vulnerability', 'Vulnerability'), ('CVE', 'Cve'), ('Trending CVE', 'Trending Cve')], max_length=15)),
                ('value', models.TextField(blank=True, max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='filter_value')])),
                ('enabled', models.BooleanField(default=True)),
                ('subscribe_all_members', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='projects.project')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('value__isnull', False)), fields=('project', 'item', 'value'), name='unique_alerts_1'), models.UniqueConstraint(condition=models.Q(('value__isnull', True)), fields=('project', 'item'), name='unique_alerts_2')],
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
    ]
