# Generated by Django 5.2.16 on 2026-08-10 09:25
# Touched: the SMTPSettings table is initialized with default SMTP settings

from typing import Any

import django.core.validators
import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


def create_default_smtp_settings(apps: Any, schema_editor: Any) -> None:
    """Create the SMTP configuration, with no server until the users set one.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is created.
    """
    apps.get_model("email", "SMTPSettings").objects.get_or_create(
        pk=1,
        defaults={"host": None, "port": 587, "username": None, "_password": None, "tls": True},
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(blank=True, max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET'])])),
                ('port', models.IntegerField(blank=True, default=587, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('username', models.TextField(blank=True, max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='name')])),
                ('_password', models.TextField(blank=True, db_column='password', max_length=200, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['SECRET'], code='api_token')])),
                ('tls', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.RunPython(create_default_smtp_settings, migrations.RunPython.noop),
    ]
