# Generated by Django 3.2.13 on 2022-04-23 11:29

from django.db import migrations, models
import django.db.models.deletion
import security.input_validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rq_job_id', models.TextField(blank=True, max_length=50, null=True)),
                ('intensity', models.IntegerField(choices=[(1, 'Sneaky'), (2, 'Low'), (3, 'Normal'), (4, 'Hard'), (5, 'Insane')], default=3)),
                ('status', models.TextField(choices=[('Requested', 'Requested'), ('Skipped', 'Skipped'), ('Running', 'Running'), ('Cancelled', 'Cancelled'), ('Error', 'Error'), ('Completed', 'Completed')], default='Requested', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_in', models.IntegerField(blank=True, null=True, validators=[security.input_validation.validate_time_amount])),
                ('scheduled_time_unit', models.TextField(blank=True, choices=[('Minutes', 'Minutes'), ('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'Weeks')], max_length=10, null=True)),
                ('repeat_in', models.IntegerField(blank=True, null=True, validators=[security.input_validation.validate_time_amount])),
                ('repeat_time_unit', models.TextField(blank=True, choices=[('Minutes', 'Minutes'), ('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'Weeks')], max_length=10, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.configuration')),
            ],
        ),
    ]
