# Generated by Django 3.2.12 on 2022-02-05 19:14

from django.db import migrations, models
import security.otp


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField(choices=[(1, 'Sneaky'), (2, 'Low'), (3, 'Normal'), (4, 'Hard'), (5, 'Insane')], default=3)),
                ('chat_id', models.IntegerField(unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('otp', models.TextField(blank=True, max_length=200, null=True, unique=True)),
                ('otp_expiration', models.DateTimeField(blank=True, default=security.otp.get_expiration, null=True)),
            ],
        ),
    ]
