# Generated by Django 3.2.11 on 2022-01-31 07:20

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('otp', models.TextField(blank=True, max_length=200, null=True, unique=True)),
                ('otp_expiration', models.DateTimeField(blank=True, default=users.utils.get_token_expiration, null=True)),
            ],
        ),
    ]
