title = "Rekono GitLeaks configuration"

[extend]
useDefault = true

[allowlist]
paths = [
  '''\.secrets\.baseline$''',
  '''/(tests|testing)/''',
  '''findings/enums\.py$''',
  '''config\.yaml$''',
]
