database:
  name: rekono
  user: null
  password: null
  host: 127.0.0.1
  port: 5432
frontend:
  url: https://localhost
  desktop: false
rq:
  host: 127.0.0.1
  port: 6379
security:
  allowed-hosts:
  - 127.0.0.1
  - localhost
  - ::1
  cookies:
    secure: false
tools:
  cmseek:
    directory: /usr/share/cmseek
  gittools:
    directory: /opt/GitTools
  log4j-scan:
    directory: /opt/log4j-scan
  spring4shell-scan:
    directory: /opt/spring4shell-scan
reports:
  pdf-template: null
