# Generated by Django 3.2.7 on 2021-10-11 16:45

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.TextField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.TextField(blank=True, max_length=150, null=True)),
                ('last_name', models.TextField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('otp', models.TextField(blank=True, max_length=200, null=True, unique=True)),
                ('notification_preference', models.IntegerField(blank=True, choices=[(1, 'Mail'), (2, 'Telegram')], default=1, null=True)),
                ('telegram_token', models.TextField(blank=True, max_length=100, null=True)),
                ('binaryedge_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('bing_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('censys_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('github_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('hunter_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('intelx_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('pentestTools_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('projectDiscovery_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('rocketreach_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('securityTrails_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('shodan_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('spyse_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('zoomeye_apikey', models.TextField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', users.models.RekonoUserManager()),
            ],
        ),
    ]
