# Generated by Django 5.2.16 on 2026-08-10 09:23

import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='defectdojo_engagement_by_target',
        ),
        migrations.RemoveField(
            model_name='project',
            name='defectdojo_engagement_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='defectdojo_product_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='defectdojo_synchronization',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=300, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='description')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(max_length=100, unique=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='name')]),
        ),
    ]
