# Generated by Django 5.2.16 on 2026-08-10 09:25

import django.db.models.deletion
import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0004_remove_targetport_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=100, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='key', deny_injections=True)])),
                ('value', models.TextField(max_length=500, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='value', deny_injections=True)])),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='http_headers', to='targets.target')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='http_headers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('key'), condition=models.Q(('target__isnull', True), ('user__isnull', True)), name='unique_http_headers'), models.UniqueConstraint(models.F('user'), models.F('key'), condition=models.Q(('target__isnull', True)), name='unique_http_headers_2'), models.UniqueConstraint(models.F('target'), models.F('key'), condition=models.Q(('user__isnull', True)), name='unique_http_headers_3')],
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
    ]
