# Generated by Django 5.2.16 on 2026-08-10 09:25

import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirusTotalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_api_token', models.TextField(blank=True, db_column='api_token', max_length=64, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['SECRET'], code='api_token')])),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
    ]
