# Generated by Django 5.2.16 on 2026-08-10 09:25
# Touched: the model is only created in the migration state, since its table already exists with
# this shape, renamed from the targets app by targets.0003_prepare_targetport_move

import django.core.validators
import django.db.models.deletion
import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0003_prepare_targetport_move'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TargetPort',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                        ('path', models.TextField(blank=True, max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['PATH'], code='path')])),
                        ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_ports', to='targets.target')),
                    ],
                    options={
                        'constraints': [models.UniqueConstraint(fields=('target', 'port'), name='unique_target_port')],
                    },
                    bases=(models.Model, framework.logging.LoggingEntity),
                ),
            ],
            database_operations=[],
        ),
    ]
