# Generated by Django 3.2.7 on 2021-11-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('executions', '0002_execution_task'),
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability', to='findings.technology'),
        ),
        migrations.AddField(
            model_name='technology',
            name='enumeration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='findings.enumeration'),
        ),
        migrations.AddField(
            model_name='technology',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='executions.execution'),
        ),
        migrations.AddField(
            model_name='technology',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_technologies', to='findings.technology'),
        ),
        migrations.AddField(
            model_name='technology',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='osint',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osint', to='executions.execution'),
        ),
        migrations.AddField(
            model_name='osint',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osint', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='host',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='executions.execution'),
        ),
        migrations.AddField(
            model_name='host',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='exploit',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exploit', to='executions.execution'),
        ),
        migrations.AddField(
            model_name='exploit',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exploit', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='exploit',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exploit', to='findings.technology'),
        ),
        migrations.AddField(
            model_name='exploit',
            name='vulnerability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exploit', to='findings.vulnerability'),
        ),
        migrations.AddField(
            model_name='enumeration',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enumeration', to='executions.execution'),
        ),
        migrations.AddField(
            model_name='enumeration',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enumeration', to='findings.host'),
        ),
        migrations.AddField(
            model_name='enumeration',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enumeration', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='enumeration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='findings.enumeration'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='executions.execution'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='credential',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='executions.execution'),
        ),
        migrations.AddField(
            model_name='credential',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='tasks.task'),
        ),
    ]
