# Generated by Django 3.2.13 on 2022-04-23 11:29

import django.db.models.deletion
import input_types.base
import security.input_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(max_length=100)),
                ('type', models.TextField(choices=[('Private IP', 'Private Ip'), ('Public IP', 'Public Ip'), ('Network', 'Network'), ('IP range', 'Ip Range'), ('Domain', 'Domain')], max_length=10)),
                ('defectdojo_engagement_id', models.IntegerField(blank=True, null=True, validators=[security.input_validation.validate_number])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='projects.project')),
            ],
            bases=(models.Model, input_types.base.BaseInput),
        ),
        migrations.CreateModel(
            name='TargetPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(validators=[security.input_validation.validate_number])),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_ports', to='targets.target')),
            ],
            bases=(models.Model, input_types.base.BaseInput),
        ),
        migrations.CreateModel(
            name='TargetVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.TextField(max_length=20, validators=[security.input_validation.validate_cve])),
                ('target_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_vulnerabilities', to='targets.targetport')),
            ],
            bases=(models.Model, input_types.base.BaseInput),
        ),
        migrations.CreateModel(
            name='TargetTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, validators=[security.input_validation.validate_name])),
                ('version', models.TextField(blank=True, max_length=100, null=True, validators=[security.input_validation.validate_name])),
                ('target_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_technologies', to='targets.targetport')),
            ],
            bases=(models.Model, input_types.base.BaseInput),
        ),
        migrations.CreateModel(
            name='TargetEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(max_length=500)),
                ('target_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_endpoints', to='targets.targetport')),
            ],
            bases=(models.Model, input_types.base.BaseInput),
        ),
        migrations.AddConstraint(
            model_name='targetvulnerability',
            constraint=models.UniqueConstraint(fields=('target_port', 'cve'), name='unique target vulnerability'),
        ),
        migrations.AddConstraint(
            model_name='targettechnology',
            constraint=models.UniqueConstraint(fields=('target_port', 'name', 'version'), name='unique target technology'),
        ),
        migrations.AddConstraint(
            model_name='targetport',
            constraint=models.UniqueConstraint(fields=('target', 'port'), name='unique target port'),
        ),
        migrations.AddConstraint(
            model_name='targetendpoint',
            constraint=models.UniqueConstraint(fields=('target_port', 'endpoint'), name='unique target endpoint'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(fields=('project', 'target'), name='unique target'),
        ),
    ]
