# Generated by Django 5.2.16 on 2026-08-10 09:23
# Touched: renamed from 0003, and the target ports are only removed from the migration state, since
# targets.0003_prepare_targetport_move already renamed their table for the target_ports app

import security.validators.enums
import security.validators.target_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_remove_authentication_credential_and_more'),
        ('projects', '0003_remove_project_defectdojo_engagement_by_target_and_more'),
        ('targets', '0003_prepare_targetport_move'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='target',
            name='unique target',
        ),
        migrations.RemoveField(
            model_name='target',
            name='defectdojo_engagement_id',
        ),
        migrations.AlterField(
            model_name='target',
            name='target',
            field=models.TextField(max_length=100, validators=[security.validators.target_validator.TargetValidator(security.validators.enums.Regex['TARGET'])]),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(fields=('project', 'target'), name='unique_target'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='targetport',
                    name='target',
                ),
                migrations.DeleteModel(
                    name='TargetPort',
                ),
            ],
            database_operations=[],
        ),
    ]
