# Generated by Django 5.2.16 on 2026-08-10 09:25
# Touched: the Integration table is initialized with default integrations

from typing import Any

import framework.logging
from django.db import migrations, models

DEFAULT_INTEGRATIONS = [
    {
        "key": "defectdojo",
        "name": "DefectDojo",
        "description": "Vulnerability management platform where Rekono will import findings when synchronization is enabled at project level",
        "enabled": False,
        "reference": "https://www.defectdojo.com/",
        "icon": "https://defectdojo.com/hubfs/DefectDojo_Symbol_Color-1.png",
    },
    {
        "key": "nvdnist",
        "name": "NVD NIST",
        "description": "National Vulnerability Database from where Rekono will get CVE information to enrich findings information",
        "enabled": True,
        "reference": "https://nvd.nist.gov/",
        "icon": "https://nvd.nist.gov/site-media/images/favicons/favicon-32x32.png",
    },
    {
        "key": "hacktricks",
        "name": "HackTricks",
        "description": "Wiki with extensive documentation about hacking techniques and tricks, that Rekono will link the detected findings to",
        "enabled": True,
        "reference": "https://hacktricks.wiki/",
        "icon": "https://hacktricks.wiki/en/favicon.svg",
    },
    {
        "key": "cvecrowd",
        "name": "CVE Crowd",
        "description": "Most trending CVEs based on their impact on social media, so Rekono will trigger alerts when one of the detected CVEs is in the spot",
        "enabled": False,
        "reference": "https://cvecrowd.com/",
        "icon": "https://cvecrowd.com/static/img/icon-small-crowd.svg",
    },
    {
        "key": "virustotal",
        "name": "Virus Total",
        "description": "Malware analysis platform whose reputation data will be used by Rekono to enrich the metadata of the identified hosts",
        "enabled": False,
        "reference": "https://www.virustotal.com/",
        "icon": "https://www.virustotal.com/gui/images/manifest/icon-192x192.png",
    },
    {
        "key": "ghsa",
        "name": "GitHub Security Advisories",
        "description": "GitHub Security Advisories from where Rekono will get CVE information to enrich findings information",
        "enabled": True,
        "reference": "https://github.com/advisories",
        "icon": "https://github.com/fluidicon.png",
    },
    {
        "key": "euvd",
        "name": "EU Vulnerability Database",
        "description": "European Union Vulnerability Database from where Rekono will get CVE information to enrich findings information",
        "enabled": True,
        "reference": "https://euvd.enisa.europa.eu/homepage",
        "icon": "https://euvd.enisa.europa.eu/favicon.ico",
    },
    {
        "key": "osv",
        "name": "Open Source Vulnerabilities",
        "description": "Open Source Vulnerabilities from where Rekono will get CVE information to enrich findings information",
        "enabled": True,
        "reference": "https://osv.dev/",
        "icon": "https://osv.dev/static/img/favicon-32x32.png",
    },
    {
        "key": "first",
        "name": "FIRST EPSS",
        "description": "FIRST Exploit Prediction Scoring System from where Rekono will get EPSS scores and percentiles for detected CVEs",
        "enabled": True,
        "reference": "https://first.org/epss",
        "icon": "https://www.first.org/favicon.ico",
    },
    {
        "key": "vulncheck",
        "name": "VulnCheck NVD++",
        "description": "VulnCheck NVD++ from where Rekono will get CVE information with additional threat intelligence to enrich findings information",
        "enabled": False,
        "reference": "https://www.vulncheck.com/nvd2",
        "icon": "https://vulncheck.com/favicon.ico",
    },
]


def create_default_integrations(apps: Any, schema_editor: Any) -> None:
    """Create the integrations with the external platforms that Rekono works with.

    Every integration is new, since the table is created by this same migration, and each
    one is matched by its key, which is how the platform code reads its own integration.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is created.
    """
    model = apps.get_model("integrations", "Integration")
    for integration in DEFAULT_INTEGRATIONS:
        model.objects.get_or_create(key=integration["key"], defaults=integration)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=100, unique=True)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('reference', models.TextField(max_length=250)),
                ('icon', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.RunPython(create_default_integrations, migrations.RunPython.noop),
    ]
