'''List of available conversation states.'''

SELECT_PROJECT = 0
SELECT_TARGET = 1
SELECT_TARGET_PORT = 2
SELECT_AUTHENTICATION_TYPE = 3
SELECT_PROCESS = 4
SELECT_TOOL = 5
SELECT_CONFIGURATION = 6
SELECT_INTENSITY = 7
SELECT_WORDLIST = 8
EXECUTE = 9
CREATE = 10
CREATE_RELATED = 11
