'''List of available conversation states.'''

SELECT_PROJECT = 0
SELECT_TARGET = 1
SELECT_TARGET_PORT = 2
SELECT_PROCESS = 3
SELECT_TOOL = 4
SELECT_CONFIGURATION = 5
SELECT_WORDLIST = 6
SELECT_INTENSITY = 7
EXECUTE = 8
CREATE = 9
