# Generated by Django 5.2.16 on 2026-08-10 09:25

import django.db.models.deletion
import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('name', models.TextField(max_length=100, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='name')])),
                ('expiration', models.DateTimeField(blank=True, null=True, validators=[security.validators.input_validator.FutureDatetimeValidator(code='expiration')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'user'), name='unique_api_token')],
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
    ]
