# Generated by Django 5.2.16 on 2026-08-10 09:25
# Touched: the API tokens issued by version 1.x are migrated into the ApiToken table

from typing import Any

import django.db.models.deletion
import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.conf import settings
from django.db import connection, migrations, models

from security.cryptography import Crypto

# Version 1.x issued one token per user, so one name identifies all of them
MIGRATED_TOKEN_NAME = "Rekono 1.x"


def migrate_1x_api_tokens(apps: Any, schema_editor: Any) -> None:
    """Create an API token for each one that version 1.x issued.

    Version 1.x used the token model of Django REST Framework, which keeps the value as plain
    text, so it's hashed here the way that version 2.x stores it, and the clients keep
    authenticating with the token that they already have. The tokens are created without an
    expiration date, since the ones of version 1.x never expired.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    # A fresh installation never had the table that version 1.x kept its tokens in
    if "authtoken_token" not in connection.introspection.table_names():
        return
    with connection.cursor() as cursor:
        cursor.execute("SELECT key, user_id, created FROM authtoken_token")
        tokens = cursor.fetchall()
    model = apps.get_model("api_tokens", "ApiToken")
    for key, user_id, created in tokens:
        api_token, is_new = model.objects.get_or_create(
            key=Crypto.hash(key), defaults={"user_id": user_id, "name": MIGRATED_TOKEN_NAME}
        )
        if is_new:
            # The creation date is written apart, since auto_now_add would overwrite the real created date
            model.objects.filter(pk=api_token.pk).update(created=created)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('name', models.TextField(max_length=100, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='name')])),
                ('expiration', models.DateTimeField(blank=True, null=True, validators=[security.validators.input_validator.FutureDatetimeValidator(code='expiration')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'user'), name='unique_api_token')],
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.RunPython(migrate_1x_api_tokens, migrations.RunPython.noop),
    ]
