FROM node:19.0.1-alpine

RUN mkdir /code
COPY /rekono/frontend /code

RUN apk update && apk add curl

ENV NODE_OPTIONS --openssl-legacy-provider

WORKDIR /code
RUN npm install -g serve

RUN adduser --disabled-password rekono
RUN chown -R rekono /code
USER rekono

RUN npm install
RUN npx browserslist@latest --update-db
RUN npm run build