# Generated by Django 5.2.16 on 2026-08-10 09:23

import django.core.validators
import django.db.models.deletion
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_remove_inputtechnology_unique_input_technology_and_more'),
        ('processes', '0004_remove_step_unique_step_rename_creator_process_owner_and_more'),
        ('target_ports', '__first__'),
        ('tasks', '0002_initial'),
        ('tools', '0004_remove_argument_unique_argument_and_more'),
        ('wordlists', '0004_rename_creator_wordlist_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='scheduled_in',
        ),
        migrations.RemoveField(
            model_name='task',
            name='scheduled_time_unit',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tool',
        ),
        migrations.AddField(
            model_name='task',
            name='input_technologies',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='parameters.inputtechnology'),
        ),
        migrations.AddField(
            model_name='task',
            name='input_vulnerabilities',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='parameters.inputvulnerability'),
        ),
        migrations.AddField(
            model_name='task',
            name='target_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='target_ports.targetport'),
        ),
        migrations.AlterField(
            model_name='task',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tools.configuration'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='processes.process'),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat_in',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, validators=[security.validators.input_validator.FutureDatetimeValidator(code='scheduled_at')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='wordlists',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='wordlists.wordlist'),
        ),
    ]
