# Generated by Django 5.2.16 on 2026-08-10 09:23
# Touched: the removal of the version 1.x tool was moved after its configuration is resolved

from typing import Any

import django.core.validators
import django.db.models.deletion
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models


def migrate_1x_task_tool(apps: Any, schema_editor: Any) -> None:
    """Give the version 1.x tasks the default configuration of their tool.

    Version 1.x let the users pick a tool without choosing one of its configurations, while
    version 2.x only keeps the configuration, so a task would stop saying what it runs.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    configuration_model = apps.get_model("tools", "Configuration")
    defaults: dict[int, int] = {}
    for task in apps.get_model("tasks", "Task").objects.filter(configuration__isnull=True, tool__isnull=False):
        if task.tool_id not in defaults:
            configuration = configuration_model.objects.filter(tool_id=task.tool_id, default=True).first()
            defaults[task.tool_id] = configuration.pk if configuration else None
        if defaults[task.tool_id]:
            task.configuration_id = defaults[task.tool_id]
            task.save(update_fields=["configuration"])


def revert_1x_task_tool(apps: Any, schema_editor: Any) -> None:
    """Give the tasks back the tool that version 1.x kept beside their configuration.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    tools = dict(apps.get_model("tools", "Configuration").objects.values_list("pk", "tool_id"))
    for task in apps.get_model("tasks", "Task").objects.filter(configuration__isnull=False):
        task.tool_id = tools.get(task.configuration_id)
        task.save(update_fields=["tool"])


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_remove_inputtechnology_unique_input_technology_and_more'),
        ('processes', '0004_remove_step_unique_step_rename_creator_process_owner_and_more'),
        ('target_ports', '__first__'),
        ('tasks', '0002_initial'),
        ('tools', '0004_remove_argument_unique_argument_and_more'),
        ('wordlists', '0004_rename_creator_wordlist_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='scheduled_in',
        ),
        migrations.RemoveField(
            model_name='task',
            name='scheduled_time_unit',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='input_technologies',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='parameters.inputtechnology'),
        ),
        migrations.AddField(
            model_name='task',
            name='input_vulnerabilities',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='parameters.inputvulnerability'),
        ),
        migrations.AddField(
            model_name='task',
            name='target_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='target_ports.targetport'),
        ),
        migrations.AlterField(
            model_name='task',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tools.configuration'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='processes.process'),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat_in',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, validators=[security.validators.input_validator.FutureDatetimeValidator(code='scheduled_at')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='wordlists',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='wordlists.wordlist'),
        ),
        migrations.RunPython(migrate_1x_task_tool, revert_1x_task_tool),
        migrations.RemoveField(
            model_name='task',
            name='tool',
        ),
    ]
