# Generated by Django 5.2.16 on 2026-08-10 09:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_types', '0003_rename_callback_model_inputtype_fallback_model_and_more'),
        ('tools', '0003_auto_20230105_1642'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='argument',
            name='unique argument',
        ),
        migrations.RemoveConstraint(
            model_name='configuration',
            name='unique configuration',
        ),
        migrations.RemoveConstraint(
            model_name='input',
            name='unique input',
        ),
        migrations.RemoveConstraint(
            model_name='output',
            name='unique output',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='arguments',
            new_name='command_template',
        ),
        migrations.RemoveField(
            model_name='argument',
            name='tool',
        ),
        migrations.AddField(
            model_name='argument',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='tools.configuration'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='default_scanned_port',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='ignore_exit_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='run_directory_property',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='script',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='script_directory_property',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='version',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='version_argument',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='command',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='defectdojo_scan_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='argument',
            constraint=models.UniqueConstraint(fields=('configuration', 'name'), name='unique_argument'),
        ),
        migrations.AddConstraint(
            model_name='configuration',
            constraint=models.UniqueConstraint(fields=('tool', 'name'), name='unique_configuration'),
        ),
        migrations.AddConstraint(
            model_name='input',
            constraint=models.UniqueConstraint(fields=('argument', 'order'), name='unique_input'),
        ),
        migrations.AddConstraint(
            model_name='output',
            constraint=models.UniqueConstraint(fields=('configuration', 'type'), name='unique_output'),
        ),
    ]
