# Generated by Django 3.2.15 on 2022-10-22 08:41

from django.db import migrations, models
import security.input_validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_files_max_mb', models.IntegerField(default=512, validators=[security.input_validation.validate_upload_file_size])),
                ('telegram_bot_token', models.TextField(blank=True, null=True, validators=[security.input_validation.validate_telegram_token])),
                ('defect_dojo_url', models.TextField(blank=True, null=True, validators=[security.input_validation.validate_url])),
                ('defect_dojo_api_key', models.TextField(blank=True, null=True, validators=[security.input_validation.validate_defect_dojo_api_key])),
                ('defect_dojo_verify_tls', models.BooleanField(default=True)),
                ('defect_dojo_tag', models.TextField(default='rekono', validators=[security.input_validation.validate_name])),
                ('defect_dojo_product_type', models.TextField(default='Rekono Project', validators=[security.input_validation.validate_name])),
                ('defect_dojo_test_type', models.TextField(default='Rekono Findings Import', validators=[security.input_validation.validate_name])),
                ('defect_dojo_test', models.TextField(default='Rekono Test', validators=[security.input_validation.validate_name])),
            ],
        ),
    ]
