FROM node:22.15.1-bookworm-slim AS build

COPY src/frontend /code
WORKDIR /code

RUN npm install && npm run build


FROM gcr.io/distroless/nodejs22-debian12:nonroot AS base

COPY --from=build --chown=65532:65532 /code/.output /code

WORKDIR /code
EXPOSE 3000

CMD ["server/index.mjs"]
