events {
    worker_connections 1024;
}

http {
    server_tokens off;
    client_max_body_size 600m;

    upstream backend {
        server backend:8000;
    }

    upstream frontend {
        server frontend:3000;
    }

    server {
        listen 80;
        listen [::]:80;

        server_name rekono.com;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        http2 on;

        server_name rekono.com;

        ssl_certificate /etc/nginx/tls/certificate.crt;
        ssl_certificate_key /etc/nginx/tls/privatekey.key;

        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;
        ssl_session_tickets off;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "CHACHA20-POLY1305-SHA256;ECDHE-ECDSA-CHACHA20-POLY1305-SHA256;ECDHE-ECDSA-AES128-GCM-SHA256;ECDHE-ECDSA-AES256-GCM-SHA384";

        location /api/_nuxt_icon/ {
            proxy_redirect off;

            proxy_pass http://frontend;
        }

        location /api/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_buffering off;
            proxy_redirect off;

            proxy_pass_header Cache-Control;
            proxy_pass_header Content-Security-Policy;
            proxy_pass_header Referrer-Policy;
            proxy_pass_header Server;
            proxy_pass_header X-Content-Type-Options;
            proxy_pass_header X-Frame-Options;

            proxy_pass http://backend;
        }

        location / {
            proxy_redirect off;

            proxy_pass_header Server;

            add_header Cache-Control no-store;
            add_header Content-Security-Policy "default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; connect-src 'self' gateway.umami.is api.iconify.design; img-src 'self' data: www.kali.org fullhunt.io avatars.githubusercontent.com gitleaks.io owasp.org vulncheck.com www.first.org osv.dev euvd.enisa.europa.eu github.com www.virustotal.com cvecrowd.com hacktricks.wiki nvd.nist.gov defectdojo.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' cloud.umami.is; style-src 'self' 'unsafe-inline'; font-src 'self'; report-uri /api/csp-report-uri/; report-to csp-endpoint";
            add_header Reporting-Endpoints 'csp-endpoint="/api/csp-report-to/"';
            add_header Referrer-Policy no-Referrer;
            add_header X-Content-Type-Options nosniff;
            add_header X-Frame-Options DENY;

            proxy_pass http://frontend;
        }
    }
}