# Generated by Django 5.2.16 on 2026-08-10 09:23
# Touched: the TelegramSettings table is initialized with default Telegram settings

from typing import Any

import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


def create_default_telegram_settings(apps: Any, schema_editor: Any) -> None:
    """Create the Telegram configuration, with no token until the users set one.

    The token of a version 1.x deployment is copied over this default by
    settings.0002_settings, which runs afterwards, so an upgrade keeps the one that it had.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is created.
    """
    apps.get_model("telegram_app", "TelegramSettings").objects.get_or_create(pk=1, defaults={"_token": None})


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0002_telegramchat_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_token', models.TextField(blank=True, db_column='token', max_length=200, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['SECRET'], code='api_token')])),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='otp',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True, validators=[security.validators.input_validator.FutureDatetimeValidator(code='otp_expiration')]),
        ),
        migrations.RunPython(create_default_telegram_settings, migrations.RunPython.noop),
    ]
