# Generated by Django 5.2.16 on 2026-08-10 09:25

import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CveCrowdCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.TextField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.CreateModel(
            name='CveCrowdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_api_token', models.TextField(blank=True, db_column='api_token', max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['SECRET'], code='api_token')])),
                ('trending_span_days', models.IntegerField(choices=[(1, '1 day'), (7, '7 days'), (30, '30 days')], default=1)),
                ('execute_per_execution', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
    ]
