# Generated by Django 5.2.16 on 2026-08-10 09:23
# Touched: the deletion of the version 1.x system model was split into settings.0004_delete_system,
# so settings.0003_migrate_1x_configuration can read its configuration before it's dropped

import django.core.validators
import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_uploaded_file_mb', models.IntegerField(default=512, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(3072)])),
                ('all_proxy', models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('http_proxy', models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('https_proxy', models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('ftp_proxy', models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('no_proxy', models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('auto_fix_findings', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
    ]
