# Generated by Django 5.2.16 on 2026-08-10 09:23
# Touched: migration of version 1.x system model's data and Settings table initialization

from typing import Any

import django.core.validators
import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models

from rekono.settings import CONFIG
from security.cryptography import Crypto


def _encrypt(value: str | None) -> str | None:
    """Encrypt a version 1.x secret the way that the version 2.x models store it.

    BaseEncrypted builds its encryptor from the configured key, and stores the value as
    plain text when there is none, so this does the same instead of using the models,
    whose historical versions have none of that behaviour.

    Returns:
        The encrypted secret, the plain one when no encryption key is configured, or None
        when there is no secret to migrate.
    """
    if not value:
        return None
    return Crypto(CONFIG.encryption_key).encrypt(value) if CONFIG.encryption_key else value


def _decrypt(value: str | None) -> str | None:
    """Recover a secret stored by the version 2.x models, as version 1.x kept it.

    Mirrors _encrypt, so a value that was stored as plain text because no encryption key
    was configured is returned untouched.

    Returns:
        The plain secret, or None when there is no secret to recover.
    """
    if not value:
        return None
    return Crypto(CONFIG.encryption_key).decrypt(value) if CONFIG.encryption_key else value


def create_default_settings(apps: Any, schema_editor: Any) -> None:
    """Create the Rekono configuration that a new deployment starts with.

    The configuration of a version 1.x deployment is copied over these defaults right after,
    so an upgrade keeps the values that it had and gets the ones that version 2.x added.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is created.
    """
    apps.get_model("settings", "Settings").objects.get_or_create(
        pk=1,
        defaults={
            "max_uploaded_file_mb": 512,
            "all_proxy": None,
            "http_proxy": None,
            "https_proxy": None,
            "ftp_proxy": None,
            "no_proxy": None,
            "auto_fix_findings": True,
        },
    )


def migrate_1x_configuration(apps: Any, schema_editor: Any) -> None:
    """Copy the version 1.x configuration into the models that replaced it.

    Version 1.x kept the whole configuration in one system model, which version 2.x split
    into the settings and the configuration of each platform. Its DefectDojo product type,
    test type and test names are dropped, since version 2.x builds those names itself and
    has no setting to keep them in, and its DefectDojo integration is enabled when it was
    configured, so the synchronization keeps working after the upgrade.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    system = apps.get_model("settings", "System").objects.first()
    if not system:
        return
    apps.get_model("settings", "Settings").objects.update_or_create(
        pk=1,
        defaults={"max_uploaded_file_mb": system.upload_files_max_mb},
    )
    apps.get_model("telegram_app", "TelegramSettings").objects.update_or_create(
        pk=1,
        defaults={"_token": _encrypt(system.telegram_bot_token)},
    )
    apps.get_model("defectdojo", "DefectDojoSettings").objects.update_or_create(
        pk=1,
        defaults={
            "server": system.defect_dojo_url,
            "_api_token": _encrypt(system.defect_dojo_api_key),
            "tls_validation": system.defect_dojo_verify_tls,
            "tag": system.defect_dojo_tag,
            # Version 1.x had no setting for this, so an upgrade keeps the format that it always sent
            "date_format": "%Y-%m-%d",
        },
    )
    # Version 1.x had no way to enable and disable a platform, so it synchronized the findings
    # whenever DefectDojo was configured, and the integrations are created disabled. Whether the
    # server still answers is checked when the findings are sent
    if system.defect_dojo_url and system.defect_dojo_api_key:
        apps.get_model("integrations", "Integration").objects.filter(key="defectdojo").update(enabled=True)


def revert_1x_configuration(apps: Any, schema_editor: Any) -> None:
    """Put the configuration back in the one system model that version 1.x kept it in.

    The DefectDojo product type, test type and test names take the defaults of version 1.x,
    since version 2.x builds those names itself and has nowhere to keep them, and the
    integrations are left alone, since version 1.x had no way to enable or disable them.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    settings = apps.get_model("settings", "Settings").objects.filter(pk=1).first()
    if not settings:
        return
    telegram = apps.get_model("telegram_app", "TelegramSettings").objects.filter(pk=1).first()
    defectdojo = apps.get_model("defectdojo", "DefectDojoSettings").objects.filter(pk=1).first()
    apps.get_model("settings", "System").objects.update_or_create(
        pk=1,
        defaults={
            "upload_files_max_mb": settings.max_uploaded_file_mb,
            "telegram_bot_token": _decrypt(telegram._token) if telegram else None,
            "defect_dojo_url": defectdojo.server if defectdojo else None,
            "defect_dojo_api_key": _decrypt(defectdojo._api_token) if defectdojo else None,
            "defect_dojo_verify_tls": defectdojo.tls_validation if defectdojo else True,
            "defect_dojo_tag": (defectdojo.tag if defectdojo else None) or "rekono",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('telegram_app', '0003_telegramsettings_alter_telegramchat_otp_and_more'),
        ('defectdojo', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_uploaded_file_mb', models.IntegerField(default=512, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(3072)])),
                ('all_proxy', models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('http_proxy', models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('https_proxy', models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('ftp_proxy', models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('no_proxy', models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET_REGEX'])])),
                ('auto_fix_findings', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.RunPython(create_default_settings, migrations.RunPython.noop),
        migrations.RunPython(migrate_1x_configuration, revert_1x_configuration),
        migrations.DeleteModel(name='System'),
    ]
