# Generated by Django 3.2.16 on 2023-01-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TargetEndpoint',
        ),
        migrations.DeleteModel(
            name='TargetTechnology',
        ),
        migrations.DeleteModel(
            name='TargetVulnerability',
        ),
    ]
