# Generated by Django 3.2.7 on 2021-11-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(max_length=100)),
                ('type', models.TextField(choices=[('Private IP', 'Private Ip'), ('Public IP', 'Public Ip'), ('Network', 'Network'), ('IP range', 'Ip Range'), ('Domain', 'Domain')], max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='projects.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TargetPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_ports', to='targets.target')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='targetport',
            constraint=models.UniqueConstraint(fields=('target', 'port'), name='unique target port'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(fields=('project', 'target'), name='unique target'),
        ),
    ]
