# Generated by Django 3.2.12 on 2022-02-05 11:19

from django.db import migrations, models
import django.db.models.deletion
import input_types.base
import security.input_validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(max_length=100)),
                ('type', models.TextField(choices=[('Private IP', 'Private Ip'), ('Public IP', 'Public Ip'), ('Network', 'Network'), ('IP range', 'Ip Range'), ('Domain', 'Domain')], max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='projects.project')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(models.Model, input_types.base.BaseInput),
        ),
        migrations.CreateModel(
            name='TargetPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(validators=[security.input_validation.validate_port])),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_ports', to='targets.target')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(models.Model, input_types.base.BaseInput),
        ),
        migrations.CreateModel(
            name='TargetEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(max_length=500, validators=[security.input_validation.validate_endpoint])),
                ('target_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_endpoints', to='targets.targetport')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(models.Model, input_types.base.BaseInput),
        ),
        migrations.AddConstraint(
            model_name='targetport',
            constraint=models.UniqueConstraint(fields=('target', 'port'), name='unique target port'),
        ),
        migrations.AddConstraint(
            model_name='targetendpoint',
            constraint=models.UniqueConstraint(fields=('target_port', 'endpoint'), name='unique target endpoint'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(fields=('project', 'target'), name='unique target'),
        ),
    ]
