# Generated by Django 3.2.16 on 2022-11-22 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TargetEndpoint',
        ),
    ]
