# Generated by Django 3.2.16 on 2022-12-10 23:26

from django.db import migrations, models
import django.db.models.deletion
import input_types.base
import security.input_validation


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_delete_targetendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, validators=[security.input_validation.validate_name])),
                ('credential', models.TextField(max_length=500, validators=[security.input_validation.validate_credential])),
                ('type', models.TextField(choices=[('Basic', 'Basic'), ('Bearer', 'Bearer'), ('Cookie', 'Cookie'), ('Digest', 'Digest'), ('JWT', 'Jwt'), ('NTLM', 'Ntlm')], max_length=8)),
                ('target_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_authentications', to='targets.targetport')),
            ],
            bases=(models.Model, input_types.base.BaseInput),
        ),
        migrations.AddConstraint(
            model_name='targetauthentication',
            constraint=models.UniqueConstraint(fields=('target_port', 'name', 'credential', 'type'), name='unique target authentication'),
        ),
    ]
