# Generated by Django 3.2.16 on 2022-12-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_delete_targetendpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TargetTechnology',
        ),
        migrations.DeleteModel(
            name='TargetVulnerability',
        ),
    ]
