# Generated by Django 3.2.16 on 2022-12-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_delete_targetendpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetvulnerability',
            name='target_port',
        ),
        migrations.DeleteModel(
            name='TargetTechnology',
        ),
        migrations.DeleteModel(
            name='TargetVulnerability',
        ),
    ]
