# Generated by Django 3.2.16 on 2022-12-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputtype',
            old_name='callback_target',
            new_name='callback_model',
        ),
        migrations.RenameField(
            model_name='inputtype',
            old_name='related_model',
            new_name='model',
        ),
    ]
