# Generated by Django 3.2.16 on 2022-12-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_types', '0002_auto_20221218_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtype',
            name='regular',
            field=models.BooleanField(default=True),
        ),
    ]
