# Generated by Django 5.2.16 on 2026-08-10 09:23
# Touched: the removal of the version 1.x tool was moved after its configuration is resolved, and
# the removal of its error output after the output that replaces it is copied

from typing import Any

import django.db.models.deletion
from django.db import migrations, models


def migrate_1x_execution_output(apps: Any, schema_editor: Any) -> None:
    """Append the error output of version 1.x to the output that replaced it.

    Version 1.x kept the standard output and the error output of a tool in separate fields,
    and only filled one of them, since an execution either completed or failed. Version 2.x
    runs the tools with both streams merged into the plain output, so the error output is
    appended to it instead of being lost with the field that kept it.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    model = apps.get_model("executions", "Execution")
    for execution in model.objects.exclude(output_error__isnull=True).exclude(output_error=""):
        execution.output_plain = "\n".join(filter(None, [execution.output_plain, execution.output_error]))
        execution.save(update_fields=["output_plain"])


def revert_1x_execution_output(apps: Any, schema_editor: Any) -> None:
    """Put the output of the failed executions back where version 1.x kept it.

    Version 1.x kept the whole output of a failed execution in its error output, so that's
    where the plain output of every failed execution goes, no matter which version ran it.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    apps.get_model("executions", "Execution").objects.filter(status="Error").update(
        output_error=models.F("output_plain"), output_plain=None
    )


def migrate_1x_execution_tool(apps: Any, schema_editor: Any) -> None:
    """Give the version 1.x executions the default configuration of their tool.

    Version 1.x required a tool and left the configuration empty when the users picked the tool
    without choosing one, while version 2.x only keeps the configuration, so an execution would
    stop saying what it ran.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    configuration_model = apps.get_model("tools", "Configuration")
    defaults: dict[int, int] = {}
    for execution in apps.get_model("executions", "Execution").objects.filter(
        configuration__isnull=True, tool__isnull=False
    ):
        if execution.tool_id not in defaults:
            configuration = configuration_model.objects.filter(tool_id=execution.tool_id, default=True).first()
            defaults[execution.tool_id] = configuration.pk if configuration else None
        if defaults[execution.tool_id]:
            execution.configuration_id = defaults[execution.tool_id]
            execution.save(update_fields=["configuration"])


def revert_1x_execution_tool(apps: Any, schema_editor: Any) -> None:
    """Give the executions back the tool that version 1.x kept beside their configuration.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    tools = dict(apps.get_model("tools", "Configuration").objects.values_list("pk", "tool_id"))
    for execution in apps.get_model("executions", "Execution").objects.filter(configuration__isnull=False):
        execution.tool_id = tools.get(execution.configuration_id)
        execution.save(update_fields=["tool"])


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
        ('tasks', '0002_initial'),
        ('tools', '0004_remove_argument_unique_argument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='extra_data_path',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='imported_in_defectdojo',
        ),
        migrations.AddField(
            model_name='execution',
            name='defectdojo_test_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='executed_command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='hash',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='skipped_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.configuration'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tasks.task'),
        ),
        migrations.RunPython(migrate_1x_execution_output, revert_1x_execution_output),
        migrations.RemoveField(
            model_name='execution',
            name='output_error',
        ),
        migrations.RunPython(migrate_1x_execution_tool, revert_1x_execution_tool),
        migrations.RemoveField(
            model_name='execution',
            name='tool',
        ),
    ]
