# Generated by Django 5.2.16 on 2026-08-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
        ('tasks', '0002_initial'),
        ('tools', '0004_remove_argument_unique_argument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='extra_data_path',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='imported_in_defectdojo',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='output_error',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='tool',
        ),
        migrations.AddField(
            model_name='execution',
            name='defectdojo_test_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='executed_command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='hash',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='skipped_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.configuration'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tasks.task'),
        ),
    ]
