# Generated by Django 5.2.16 on 2026-08-10 09:23

import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inputtechnology',
            name='unique input technology',
        ),
        migrations.RemoveConstraint(
            model_name='inputvulnerability',
            name='unique input vulnerability',
        ),
        migrations.RemoveField(
            model_name='inputtechnology',
            name='target',
        ),
        migrations.RemoveField(
            model_name='inputvulnerability',
            name='target',
        ),
        migrations.AlterField(
            model_name='inputtechnology',
            name='name',
            field=models.TextField(max_length=100, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='name', deny_injections=True)]),
        ),
        migrations.AlterField(
            model_name='inputtechnology',
            name='version',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='version', deny_injections=True)]),
        ),
        migrations.AlterField(
            model_name='inputvulnerability',
            name='cve',
            field=models.TextField(max_length=20, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['CVE'], code='cve', deny_injections=True)]),
        ),
    ]
