# Generated by Django 3.2.7 on 2021-11-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='type',
            field=models.TextField(choices=[('OSINT', 'Osint'), ('Host', 'Host'), ('Enumeration', 'Enumeration'), ('Endpoint', 'Endpoint'), ('Technology', 'Technology'), ('Vulnerability', 'Vulnerability'), ('Exploit', 'Exploit'), ('Credential', 'Credential'), ('Wordlist', 'Wordlist')], max_length=15),
        ),
        migrations.AlterField(
            model_name='output',
            name='type',
            field=models.TextField(choices=[('OSINT', 'Osint'), ('Host', 'Host'), ('Enumeration', 'Enumeration'), ('Endpoint', 'Endpoint'), ('Technology', 'Technology'), ('Vulnerability', 'Vulnerability'), ('Exploit', 'Exploit'), ('Credential', 'Credential'), ('Wordlist', 'Wordlist')], max_length=15),
        ),
    ]
