# Generated by Django 3.2.16 on 2023-01-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='stage',
        ),
        migrations.AddField(
            model_name='configuration',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Osint'), (2, 'Enumeration'), (3, 'Vulnerabilities'), (4, 'Services'), (5, 'Exploitation')], default=1),
            preserve_default=False,
        ),
    ]
