# Generated by Django 5.2.16 on 2026-08-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_types', '0002_auto_20221226_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputtype',
            old_name='callback_model',
            new_name='fallback_model',
        ),
        migrations.RenameField(
            model_name='inputtype',
            old_name='regular',
            new_name='relationships',
        ),
        migrations.AlterField(
            model_name='inputtype',
            name='name',
            field=models.TextField(choices=[('OSINT', 'Osint'), ('Host', 'Host'), ('Port', 'Port'), ('Path', 'Path'), ('Technology', 'Technology'), ('Credential', 'Credential'), ('Vulnerability', 'Vulnerability'), ('Exploit', 'Exploit'), ('Wordlist', 'Wordlist'), ('Authentication', 'Authentication'), ('Http Header', 'Http Header')], max_length=15),
        ),
    ]
