# Generated by Django 5.2.16 on 2026-08-10 09:23
# Touched: the data from version 1.x is migrated between the generated operations, which are
# reordered when the migrated data needs it. It covers the severities, the renamed choices and
# the fields that replace the ones that version 2.x removed

from typing import Any

import django.db.models.deletion
import security.validators.enums
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models

FINDINGS = ["OSINT", "Host", "Port", "Path", "Technology", "Credential", "Vulnerability", "Exploit"]
SEVERITIES = {"Info": 1, "Low": 2, "Medium": 3, "High": 4, "Critical": 5}
CHOICES_MIGRATED_FROM_1X = [
    # Version 2.x writes the acronym in upper case, and dropped the links, which are just URLs
    ("OSINT", "data_type", {"Url": "URL", "Link": "URL"}),
    # Version 2.x capitalizes the types instead of writing them in upper case
    ("Path", "type", {"ENDPOINT": "Endpoint", "SHARE": "Share"}),
]


def flush_deferred_constraints(schema_editor: Any) -> None:
    """Check the constraints left deferred by data migrated in the same transaction.

    Changing the severity into an integer rewrites the finding table, and PostgreSQL stops
    skipping the checks of the foreign keys that point to it once it has been rewritten. Every
    row written afterwards queues one of those checks, which are deferred until the end of the
    transaction, and PostgreSQL refuses to alter a table that has checks waiting, so the removal
    of the version 1.x fields fails unless they are checked first.

    Args:
        schema_editor: Editor of the database schema, given by the migration framework.
    """
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def migrate_1x_severities(apps: Any, schema_editor: Any) -> None:
    """Turn the severity labels of version 1.x into the numbers that replaced them.

    Version 1.x kept the severity as its label, and version 2.x orders them by keeping a number
    instead, so the labels are written as numbers while the field is still text. Without this, the
    change of the field to an integer asks PostgreSQL to read 'Low' as a number and the upgrade
    stops.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    vulnerability_model = apps.get_model("findings", "Vulnerability")
    for label, severity in SEVERITIES.items():
        vulnerability_model.objects.filter(severity=label).update(severity=str(severity))


def revert_1x_severities(apps: Any, schema_editor: Any) -> None:
    """Put the severity labels back as version 1.x kept them.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Used to check the constraints that this data leaves deferred.
    """
    vulnerability_model = apps.get_model("findings", "Vulnerability")
    for label, severity in SEVERITIES.items():
        vulnerability_model.objects.filter(severity=str(severity)).update(severity=label)
    flush_deferred_constraints(schema_editor)


def migrate_1x_choices(apps: Any, schema_editor: Any) -> None:
    """Write the values of version 1.x for the choices whose options were rewritten.

    Choices are only validated by Django, so changing them alters the model but never the data
    that the database already keeps, and the findings would hold values that no longer exist as
    an option. The OSINT links are kept as URLs, since version 2.x doesn't tell them apart and
    removing them would lose data that was gathered.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since the deferred constraints are checked later.
    """
    for model_name, field, values in CHOICES_MIGRATED_FROM_1X:
        model = apps.get_model("findings", model_name)
        for old_value, new_value in values.items():
            model.objects.filter(**{field: old_value}).update(**{field: new_value})


def revert_1x_choices(apps: Any, schema_editor: Any) -> None:
    """Put back the values that version 1.x kept for the rewritten choices.

    The OSINT links can't be told apart from the URLs anymore, so all of them come back as URLs.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since the deferred constraints are checked later.
    """
    for model_name, field, values in CHOICES_MIGRATED_FROM_1X:
        model = apps.get_model("findings", model_name)
        reverted: set[str] = set()
        for old_value, new_value in values.items():
            # Version 2.x merged several options of version 1.x into one, and they can't be told
            # apart anymore, so only the first option of the merge is written back
            if new_value in reverted:
                continue
            reverted.add(new_value)
            model.objects.filter(**{field: new_value}).update(**{field: old_value})


def migrate_1x_findings(apps: Any, schema_editor: Any) -> None:
    """Copy the active flag and the CWE of version 1.x into the fields replacing them.

    Version 1.x disabled a finding instead of deleting it, which version 2.x expresses the other
    way around, as a finding that has been fixed, so the flag is inverted rather than copied. It
    kept one CWE identifier, which version 2.x replaced by a list of them, so the identifier
    becomes the only item of that list.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Used to check the constraints that this data leaves deferred.
    """
    for finding in FINDINGS:
        apps.get_model("findings", finding).objects.filter(is_active=False).update(is_fixed=True)
    vulnerability_model = apps.get_model("findings", "Vulnerability")
    for vulnerability in vulnerability_model.objects.exclude(cwe__isnull=True).exclude(cwe=""):
        # Version 1.x kept whatever case the NVD returned, and version 2.x writes them in upper case
        vulnerability.cwes = [vulnerability.cwe.upper()]
        vulnerability.save(update_fields=["cwes"])
    flush_deferred_constraints(schema_editor)


def revert_1x_findings(apps: Any, schema_editor: Any) -> None:
    """Put the active flag and the CWE back as version 1.x kept them.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    for finding in FINDINGS:
        apps.get_model("findings", finding).objects.filter(is_fixed=True).update(is_active=False)
    vulnerability_model = apps.get_model("findings", "Vulnerability")
    for vulnerability in vulnerability_model.objects.exclude(cwes=[]):
        # Version 1.x kept one weakness, so only the first one of the list comes back
        vulnerability.cwe = vulnerability.cwes[0]
        vulnerability.save(update_fields=["cwe"])


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_remove_execution_extra_data_path_and_more'),
        ('findings', '0002_alter_osint_data_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='address',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='path',
            old_name='extra',
            new_name='extra_info',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='host',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='host',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='host',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='path',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='path',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='path',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='port',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='port',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='port',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='osvdb',
        ),
        migrations.AddField(
            model_name='credential',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credential',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credential',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AddField(
            model_name='exploit',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exploit',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exploit',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exploit',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exploit',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AddField(
            model_name='host',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='city',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='country',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='domain',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='host',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='hacktricks_link',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='malicious_analysis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='reputation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='suspicious_analysis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='total_analysis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='whois',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osint',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='osint',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AddField(
            model_name='path',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='path',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='path',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='port',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='hacktricks_link',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technology',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='hacktricks_link',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_base_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_vector',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_version',
            field=models.TextField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cwes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='epss_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='epss_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='euvd_id',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='ghsa_id',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='osv_generic_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='remediation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AlterField(
            model_name='credential',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='credential', to='findings.technology'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='host',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='osint',
            name='data_type',
            field=models.TextField(choices=[('IP', 'Ip'), ('Domain', 'Domain'), ('VHOST', 'Vhost'), ('URL', 'Url'), ('Email', 'Email'), ('ASN', 'Asn'), ('Username', 'User'), ('Password', 'Password')], max_length=10),
        ),
        migrations.AlterField(
            model_name='osint',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='path',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='path',
            name='type',
            field=models.TextField(choices=[('Endpoint', 'Endpoint'), ('Share', 'Share')], default='Endpoint'),
        ),
        migrations.AlterField(
            model_name='port',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='port',
            name='status',
            field=models.TextField(choices=[('Open', 'Open'), ('Open - Filtered', 'Open Filtered'), ('Filtered', 'Filtered'), ('Closed', 'Closed'), ('Closed - Filtered', 'Closed Filtered')], default='Open', max_length=17),
        ),
        migrations.AlterField(
            model_name='technology',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='cve',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.RunPython(migrate_1x_severities, revert_1x_severities),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Info'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=3),
        ),
        migrations.RunPython(migrate_1x_choices, revert_1x_choices),
        migrations.RunPython(migrate_1x_findings, revert_1x_findings),
        migrations.RemoveField(
            model_name='credential',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='host',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='path',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='port',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='cwe',
        ),
    ]
