# Generated by Django 5.2.16 on 2026-08-10 09:23
# Touched: the removal of the version 1.x active flag and CWE was moved after the fields that
# replace them are added and the data is copied into them

from typing import Any

import django.db.models.deletion
import security.validators.enums
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models

FINDINGS = ["OSINT", "Host", "Port", "Path", "Technology", "Credential", "Vulnerability", "Exploit"]


def migrate_1x_findings(apps: Any, schema_editor: Any) -> None:
    """Copy the active flag and the CWE of version 1.x into the fields that replaced them.

    Version 1.x disabled a finding instead of deleting it, which version 2.x expresses the other
    way around, as a finding that has been fixed, so the flag is inverted rather than copied. It
    kept one CWE identifier, which version 2.x replaced by a list of them, so the identifier
    becomes the only item of that list.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    for finding in FINDINGS:
        apps.get_model("findings", finding).objects.filter(is_active=False).update(is_fixed=True)
    vulnerability_model = apps.get_model("findings", "Vulnerability")
    for vulnerability in vulnerability_model.objects.exclude(cwe__isnull=True).exclude(cwe=""):
        # Version 1.x kept whatever case the NVD returned, and version 2.x writes them in upper case
        vulnerability.cwes = [vulnerability.cwe.upper()]
        vulnerability.save(update_fields=["cwes"])


def revert_1x_findings(apps: Any, schema_editor: Any) -> None:
    """Put the active flag and the CWE back as version 1.x kept them.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    for finding in FINDINGS:
        apps.get_model("findings", finding).objects.filter(is_fixed=True).update(is_active=False)
    vulnerability_model = apps.get_model("findings", "Vulnerability")
    for vulnerability in vulnerability_model.objects.exclude(cwes=[]):
        # Version 1.x kept one weakness, so only the first one of the list comes back
        vulnerability.cwe = vulnerability.cwes[0]
        vulnerability.save(update_fields=["cwe"])


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_remove_execution_extra_data_path_and_more'),
        ('findings', '0002_alter_osint_data_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='address',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='path',
            old_name='extra',
            new_name='extra_info',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='host',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='host',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='host',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='path',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='path',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='path',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='port',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='port',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='port',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='osvdb',
        ),
        migrations.AddField(
            model_name='credential',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credential',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credential',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AddField(
            model_name='exploit',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exploit',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exploit',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exploit',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exploit',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AddField(
            model_name='host',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='city',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='country',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='domain',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='host',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='hacktricks_link',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='malicious_analysis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='reputation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='suspicious_analysis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='total_analysis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='whois',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osint',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='osint',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AddField(
            model_name='path',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='path',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='path',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='port',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='hacktricks_link',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technology',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='hacktricks_link',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_base_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_vector',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_version',
            field=models.TextField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cwes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='epss_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='epss_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='euvd_id',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='ghsa_id',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='osv_generic_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='remediation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AlterField(
            model_name='credential',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='credential', to='findings.technology'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='host',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='osint',
            name='data_type',
            field=models.TextField(choices=[('IP', 'Ip'), ('Domain', 'Domain'), ('VHOST', 'Vhost'), ('URL', 'Url'), ('Email', 'Email'), ('ASN', 'Asn'), ('Username', 'User'), ('Password', 'Password')], max_length=10),
        ),
        migrations.AlterField(
            model_name='osint',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='path',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='path',
            name='type',
            field=models.TextField(choices=[('Endpoint', 'Endpoint'), ('Share', 'Share')], default='Endpoint'),
        ),
        migrations.AlterField(
            model_name='port',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='port',
            name='status',
            field=models.TextField(choices=[('Open', 'Open'), ('Open - Filtered', 'Open Filtered'), ('Filtered', 'Filtered'), ('Closed', 'Closed'), ('Closed - Filtered', 'Closed Filtered')], default='Open', max_length=17),
        ),
        migrations.AlterField(
            model_name='technology',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='cve',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Info'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=3),
        ),
        migrations.RunPython(migrate_1x_findings, revert_1x_findings),
        migrations.RemoveField(
            model_name='credential',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='host',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='path',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='port',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='cwe',
        ),
    ]
