# Generated by Django 5.2.16 on 2026-08-10 09:23

import django.db.models.deletion
import security.validators.enums
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_remove_execution_extra_data_path_and_more'),
        ('findings', '0002_alter_osint_data_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='address',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='path',
            old_name='extra',
            new_name='extra_info',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='exploit',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='host',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='host',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='host',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='host',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='osint',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='path',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='path',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='path',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='path',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='port',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='port',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='port',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='port',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='cwe',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='osvdb',
        ),
        migrations.AddField(
            model_name='credential',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credential',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credential',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AddField(
            model_name='exploit',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exploit',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exploit',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exploit',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exploit',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exploit',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AddField(
            model_name='host',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='city',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='country',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='domain',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='host',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='hacktricks_link',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='malicious_analysis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='reputation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='suspicious_analysis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='total_analysis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='whois',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osint',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='osint',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osint',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AddField(
            model_name='path',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='path',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='path',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='port',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='hacktricks_link',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technology',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='hacktricks_link',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='auto_fixed',
            field=models.TextField(blank=True, choices=[('No longer detected by same executions', 'No Longer Detected'), ('Parent finding got fixed', 'Parent Fixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='created_from_user_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_base_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_vector',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_version',
            field=models.TextField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cwes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='epss_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='epss_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='euvd_id',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='ghsa_id',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='osv_generic_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='remediation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_comment',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='triage_comment')]),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='triage_status',
            field=models.TextField(choices=[('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ("Won't Fix", 'Wont Fix'), ('Untriaged', 'Untriaged')], default='Untriaged', max_length=15),
        ),
        migrations.AlterField(
            model_name='credential',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='credential', to='findings.technology'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='host',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='osint',
            name='data_type',
            field=models.TextField(choices=[('IP', 'Ip'), ('Domain', 'Domain'), ('VHOST', 'Vhost'), ('URL', 'Url'), ('Email', 'Email'), ('ASN', 'Asn'), ('Username', 'User'), ('Password', 'Password')], max_length=10),
        ),
        migrations.AlterField(
            model_name='osint',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='path',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='path',
            name='type',
            field=models.TextField(choices=[('Endpoint', 'Endpoint'), ('Share', 'Share')], default='Endpoint'),
        ),
        migrations.AlterField(
            model_name='port',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='port',
            name='status',
            field=models.TextField(choices=[('Open', 'Open'), ('Open - Filtered', 'Open Filtered'), ('Filtered', 'Filtered'), ('Closed', 'Closed'), ('Closed - Filtered', 'Closed Filtered')], default='Open', max_length=17),
        ),
        migrations.AlterField(
            model_name='technology',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='cve',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='executions',
            field=models.ManyToManyField(related_name='%(class)s', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Info'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=3),
        ),
    ]
