# Generated by Django 5.2.16 on 2026-08-10 09:25
# Touched: the NvdNistSettings table is initialized with default NVD NIST settings

from typing import Any

import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


def create_default_nvdnist_settings(apps: Any, schema_editor: Any) -> None:
    """Create the NVD NIST configuration, with no API token until the users set one.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is created.
    """
    apps.get_model("nvdnist", "NvdNistSettings").objects.get_or_create(pk=1, defaults={"_api_token": None})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NvdNistSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_api_token', models.TextField(blank=True, db_column='api_token', max_length=50, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['SECRET'], code='api_token')])),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.RunPython(create_default_nvdnist_settings, migrations.RunPython.noop),
    ]
