# Generated by Django 5.2.16 on 2026-08-10 09:25
# Touched: the MonitorSettings table is initialized with default monitor settings

from typing import Any

import django.core.validators
import framework.logging
from django.db import migrations, models


def create_default_monitor_settings(apps: Any, schema_editor: Any) -> None:
    """Create the monitor configuration that a new deployment starts with.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is created.
    """
    apps.get_model("monitor", "MonitorSettings").objects.get_or_create(
        pk=1,
        defaults={"rq_job_id": None, "last_monitor": None, "hour_span": 24},
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rq_job_id', models.TextField(blank=True, max_length=50, null=True)),
                ('last_monitor', models.DateTimeField(blank=True, null=True)),
                ('hour_span', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(168)])),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.RunPython(create_default_monitor_settings, migrations.RunPython.noop),
    ]
