# Generated by Django 5.2.16 on 2026-08-10 09:25

import django.core.validators
import framework.logging
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rq_job_id', models.TextField(blank=True, max_length=50, null=True)),
                ('last_monitor', models.DateTimeField(blank=True, null=True)),
                ('hour_span', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(168)])),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
    ]
