# Generated by Django 3.2.16 on 2023-01-08 12:56
# Touched: the resources app of version 1.x is called wordlists since version 2.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlists', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='type',
            field=models.TextField(choices=[('Endpoint', 'Endpoint'), ('Subdomain', 'Subdomain')], max_length=10),
        ),
    ]
