# Generated by Django 5.2.16 on 2026-08-10 09:23
# Touched: the Wordlist table is initialized with the wordlists that Rekono provides, and the
# ones that version 1.x provided and version 2.x doesn't are removed

from typing import Any

import security.validators.enums
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models

DEFAULT_WORDLISTS = [
    ("Common (dirb)", "Endpoint", "/usr/share/dirb/wordlists/common.txt"),
    ("Big (dirb)", "Endpoint", "/usr/share/dirb/wordlists/big.txt"),
    ("Small", "Endpoint", "/usr/share/dirb/wordlists/small.txt"),
    ("Spanish", "Endpoint", "/usr/share/dirb/wordlists/spanish.txt"),
    ("Apache", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/Web-Servers/Apache.txt"),
    ("Big (seclists)", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/big.txt"),
    ("Common (seclists)", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/common.txt"),
    ("Nginx", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/Web-Servers/nginx.txt"),
    ("Swagger", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/Service-Specific/Swagger.txt"),
    ("Backdoor Web Shells", "Endpoint", "/usr/share/seclists/Web-Shells/backdoor_list.txt"),
    ("Drupal 7.20", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/URLs/urls-Drupal-7.20.txt"),
    ("Joomla 3.0.3", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/URLs/urls-joomla-3.0.3.txt"),
    ("SAP", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/URLs/urls-SAP.txt"),
    ("WordPress 3.3.1", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/URLs/urls-wordpress-3.3.1.txt"),
    ("Italian", "Subdomain", "/usr/share/seclists/Discovery/DNS/italian-subdomains.txt"),
    ("Namelist", "Subdomain", "/usr/share/seclists/Discovery/DNS/namelist.txt"),
    ("Shubs subdomains", "Subdomain", "/usr/share/seclists/Discovery/DNS/shubs-subdomains.txt"),
    ("Shubs StackOverflow", "Subdomain", "/usr/share/seclists/Discovery/DNS/shubs-stackoverflow.txt"),
    ("Top 1 Million: 5000", "Subdomain", "/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt"),
    ("Top 1 Million: 20000", "Subdomain", "/usr/share/seclists/Discovery/DNS/subdomains-top1million-20000.txt"),
    ("Top 1 Million: 110000", "Subdomain", "/usr/share/seclists/Discovery/DNS/subdomains-top1million-110000.txt"),
    ("Deep Magic: Top 500", "Subdomain", "/usr/share/seclists/Discovery/DNS/deepmagic.com-prefixes-top500.txt"),
    ("Deep Magic: Top 50000", "Subdomain", "/usr/share/seclists/Discovery/DNS/deepmagic.com-prefixes-top50000.txt"),
    ("Bitquark: Top 100000", "Subdomain", "/usr/share/seclists/Discovery/DNS/bitquark-subdomains-top100000.txt"),
    ("Combined subdomains", "Subdomain", "/usr/share/seclists/Discovery/DNS/combined_subdomains.txt"),
    ("Django", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/CMS/Django.txt"),
    ("Drupal", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/CMS/Drupal.txt"),
    ("Sharepoint Enumeration", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/CMS/Sharepoint-Ennumeration.txt"),
    ("Sharepoint", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/CMS/Sharepoint.txt"),
    ("Joomla Plugins", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/CMS/joomla-plugins.fuzz.txt"),
    ("Joomla Themes", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/CMS/joomla-themes.fuzz.txt"),
    ("Sitemap Magento", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/CMS/sitemap-magento.txt"),
    ("WordPress", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/CMS/wordpress.fuzz.txt"),
    ("WordPress Plugins", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/CMS/wp-plugins.fuzz.txt"),
    ("WordPress Themes", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/CMS/wp-themes.fuzz.txt"),
    ("API Endpoints", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/api/api-endpoints.txt"),
    ("API seen in Wild", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/api/api-seen-in-wild.txt"),
    ("API Objects", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/api/objects.txt"),
    ("IPS Bill Manager API", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/api/ispsystem_billmanager_api.txt"),
    ("GraphQL", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/graphql.txt"),
    (
        "Linux Web Root Directory",
        "Endpoint",
        "/usr/share/seclists/Discovery/Web-Content/default-web-root-directory-linux.txt",
    ),
    (
        "Windows Web Root Directory",
        "Endpoint",
        "/usr/share/seclists/Discovery/Web-Content/default-web-root-directory-windows.txt",
    ),
    ("HashiCorp Consul API", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/hashicorp-consul-api.txt"),
    ("HashiCorp Vault", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/hashicorp-vault.txt"),
    ("MCP Server", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/mcp-server.txt"),
    ("SAP Analytics Cloud", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/sap-analytics-cloud.txt"),
    (
        "Confluence Administration",
        "Endpoint",
        "/usr/share/seclists/Discovery/Web-Content/Service-Specific/confluence-administration.txt",
    ),
    (
        "HP System Management Homepage",
        "Endpoint",
        "/usr/share/seclists/Discovery/Web-Content/Service-Specific/HP-System-Management-Homepage.txt",
    ),
    (
        "IBM WebSphere Application Server",
        "Endpoint",
        "/usr/share/seclists/Discovery/Web-Content/Service-Specific/IBM-WebSphere-Application-Server.txt",
    ),
    ("Jenkings Hudson", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/Service-Specific/Jenkins-Hudson.txt"),
    (
        "Keycloak IAM",
        "Endpoint",
        "/usr/share/seclists/Discovery/Web-Content/Service-Specific/Keycloak-Identity-Access-Management.txt",
    ),
    (
        "Microsoft Forefront Identity Manager",
        "Endpoint",
        "/usr/share/seclists/Discovery/Web-Content/Service-Specific/Microsoft-Forefront-Identity-Manager.txt",
    ),
    ("Oracle WebLogic", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/Service-Specific/Oracle-WebLogic.txt"),
    ("Pulse Secure VPN", "Endpoint", "/usr/share/seclists/Discovery/Web-Content/Service-Specific/PulseSecure-VPN.txt"),
]
REMOVED_WORDLISTS = [
    "Endpoints list for Dirsearch",
    "WebLogic",
    "WebSphere",
]


def create_default_wordlists(apps: Any, schema_editor: Any) -> None:
    """Create the wordlists that Rekono provides for the tools to enumerate with.

    The wordlists are matched by name, and not by path, because the packages that provide
    the files move them between releases, and both fields are unique, so matching by path
    would try to create a wordlist whose name another one already has.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is created.
    """
    model = apps.get_model("wordlists", "Wordlist")
    for name, wordlist_type, path in DEFAULT_WORDLISTS:
        wordlist, created = model.objects.get_or_create(name=name, defaults={"type": wordlist_type, "path": path})
        # The file moved, so the wordlists that Rekono provides are pointed at the new location,
        # while the ones that the users uploaded keep whatever they set
        if not created and wordlist.owner_id is None and wordlist.path != path:
            wordlist.path = path
            wordlist.save(update_fields=["path"])


def remove_old_wordlists(apps: Any, schema_editor: Any) -> None:
    """Remove the wordlists that version 1.x provided and version 2.x doesn't.

    A wordlist that a user uploaded is never removed, even when it has one of these names,
    and neither is one that a task used, since that would erase the wordlist from the
    history of an execution that ran with it.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is deleted.
    """
    used_by_tasks = apps.get_model("tasks", "Task").wordlists.through.objects.values("wordlist_id")
    apps.get_model("wordlists", "Wordlist").objects.filter(
        name__in=REMOVED_WORDLISTS, owner__isnull=True
    ).exclude(pk__in=used_by_tasks).delete()


class Migration(migrations.Migration):

    # The tasks are needed to know which wordlists can be removed
    dependencies = [
        ('tasks', '0002_initial'),
        ('wordlists', '0003_alter_wordlist_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordlist',
            old_name='creator',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='name',
            field=models.TextField(max_length=100, unique=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='name')]),
        ),
        migrations.RunPython(create_default_wordlists, migrations.RunPython.noop),
        migrations.RunPython(remove_old_wordlists, migrations.RunPython.noop),
    ]
