# Generated by Django 5.2.16 on 2026-08-10 09:23

import security.validators.enums
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlists', '0003_alter_wordlist_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordlist',
            old_name='creator',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='name',
            field=models.TextField(max_length=100, unique=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='name')]),
        ),
    ]
