# Generated by Django 5.2.16 on 2026-08-10 09:25
# Touched: the targets migration it depends on was renamed to 0004_remove_targetport_target_and_more

import django.db.models.deletion
import framework.logging
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_remove_project_defectdojo_engagement_by_target_and_more'),
        ('targets', '0004_remove_targetport_target_and_more'),
        ('tasks', '0003_remove_task_scheduled_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('Ready', 'Ready'), ('Pending', 'Pending'), ('Error', 'Error')], default='Pending', max_length=7)),
                ('format', models.TextField(choices=[('json', 'Json'), ('xml', 'Xml'), ('pdf', 'Pdf')], max_length=4)),
                ('path', models.TextField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='targets.target')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tasks.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
    ]
