<template>
  <MenuProfile>
    <v-container fluid>
      <v-row justify="center">
        <v-col cols="8">
          <BaseSection
            class="mt-5"
            title="Rekono Bot"
            :icon="enums.notificationPlatforms.Telegram.icon"
            :color="enums.notificationPlatforms.Telegram.color"
            :loading="loading ? 'blue' : undefined"
          >
            <template v-if="user && telegram && telegram.is_available" #append>
              <BaseButton
                v-if="user.telegram_chat === null"
                :link="`https://t.me/${telegram.bot}`"
                new-tab
              />
              <UtilsDeleteButton
                v-if="user.telegram_chat !== null"
                :id="user.telegram_chat"
                :api="api"
                icon="mdi-logout-variant"
                icon-confirmation="mdi-logout-variant"
                action="Logout"
                :text="`Your @${telegram.bot} session will be closed`"
                @completed="getProfile()"
              />
            </template>
            <v-container fluid>
              <v-row v-if="user && telegram && !telegram?.is_available">
                <v-col>
                  <v-alert
                    class="text-center"
                    color="warning"
                    icon="$warning"
                    variant="tonal"
                  >
                    <template #text>
                      <p v-if="autz.isAdmin()">
                        Telegram bot is not configured yet. Configure and enable
                        it in the
                        <v-btn
                          class="pa-0 text-none mb-1 font-weight-bold"
                          density="compact"
                          text="administration page"
                          variant="plain"
                          to="/administration/notifications"
                        />
                      </p>
                      <p v-if="!autz.isAdmin()">
                        Telegram bot is not configured yet. Ask your
                        administrator to configure and enable it
                      </p>
                    </template>
                  </v-alert>
                </v-col>
              </v-row>
              <template v-if="user && telegram && telegram?.is_available">
                <template v-if="user?.telegram_chat !== null">
                  <v-row>
                    <v-col>
                      <v-btn
                        color="blue"
                        size="x-large"
                        variant="tonal"
                        prepend-icon="mdi-robot"
                        :append-icon="enums.notificationPlatforms.Telegram.icon"
                        text="Take me to the Rekono Bot!"
                        class="mt-5"
                        block
                        autofocus
                        target="_blank"
                        :href="`https://t.me/${telegram.bot}`"
                      />
                    </v-col>
                  </v-row>
                </template>
                <template v-if="user?.telegram_chat === null">
                  <v-row>
                    <v-col>
                      <v-alert color="info" icon="$info" variant="tonal">
                        <template #text>
                          <p class="text-center">
                            Go to
                            <v-btn
                              class="pa-0 text-none mb-1 font-weight-bold"
                              density="compact"
                              :text="`@${telegram.bot}`"
                              variant="plain"
                              target="_blank"
                              :href="`https://t.me/${telegram.bot}?start=bot`"
                            />
                            and run the command
                            <span class="font-weight-bold font-italic"
                              >/start</span
                            >. Then paste here the token generated by the bot to
                            link your account
                          </p>
                        </template>
                      </v-alert>
                    </v-col>
                  </v-row>
                  <v-form v-model="valid" class="mt-5" @submit.prevent="link()">
                    <v-row>
                      <v-col>
                        <v-text-field
                          v-model="token"
                          type="password"
                          density="comfortable"
                          label="Token"
                          prepend-inner-icon="mdi-key"
                          variant="outlined"
                          :rules="[
                            (t) => !!t || 'Token is required',
                            (t) => t.length === 128 || 'Invalid token',
                          ]"
                          validate-on="input"
                          clearable
                          @update:model-value="disabled = false"
                        />
                      </v-col>
                    </v-row>
                    <v-row dense>
                      <v-col>
                        <UtilsSubmit
                          text="Link Rekono Bot"
                          class="mt-5"
                          :color="enums.notificationPlatforms.Telegram.color"
                          :disabled="disabled"
                        />
                      </v-col>
                    </v-row>
                  </v-form>
                </template>
              </template>
            </v-container>
          </BaseSection>
        </v-col>
      </v-row>
    </v-container>
  </MenuProfile>
</template>

<script setup lang="ts">
definePageMeta({ layout: false });
const alert = useAlert();
const enums = useEnums();
const autz = useAutz();
const api = useApi("/api/telegram/link/", true);
const user = ref(null);
const token = ref(null);
const valid = ref(true);
const disabled = ref(true);
const loading = ref(false);
const telegram = ref(null);
useApi("/api/telegram/settings/", true)
  .get(1)
  .then((response) => (telegram.value = response));
getProfile();

function getProfile(): void {
  useApi("/api/profile/", true)
    .get()
    .then((response) => (user.value = response));
}

function link(): void {
  if (valid.value) {
    loading.value = true;
    api
      .create({ otp: token.value })
      .then(() => {
        getProfile();
        alert("Rekono Bot has been linked to your account", "success");
        loading.value = false;
        disabled.value = true;
        token.value = null;
      })
      .catch((error) => {
        loading.value = false;
        disabled.value = true;
        token.value = null;
        if (error.statusCode === 401) {
          alert("Invalid Rekono Bot token", "error");
        }
      });
  }
}
</script>
