# Generated by Django 5.2.16 on 2026-08-10 09:23
# Touched: the Process and Step tables are initialized with the default processes

from typing import Any

import django.db.models.deletion
import security.validators.enums
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models

DEFAULT_PROCESSES = [
    {
        "name": "All tools",
        "description": (
            "Comprehensive security assessment that performs passive information gathering, port "
            "and service enumeration, web application testing, vulnerability scanning, and exploit "
            "research. This process provides complete coverage across all penetration testing "
            "phases to identify potential security weaknesses in the target infrastructure."
        ),
        "steps": [19, 30, 31, 38, 15, 21, 22, 23, 24, 25, 28, 32, 33, 34, 35, 26, 27, 39, 46, 47, 48, 42],
    },
    {
        "name": "HTTP Analysis",
        "description": (
            "Focused security assessment of web applications and HTTP services. Performs directory "
            "and endpoint enumeration, SSL/TLS configuration analysis, content management system "
            "identification, and security testing of web-based attack vectors."
        ),
        "steps": [3, 15, 21, 22, 23, 24, 25, 28, 32, 33, 26, 27, 39, 48, 42],
    },
    {
        "name": "FTP Analysis",
        "description": (
            "Specialized security assessment of FTP services. Examines FTP server configurations, "
            "tests for anonymous access, identifies common vulnerabilities and backdoors, performs "
            "SSL/TLS analysis for secure FTP implementations, and searches for applicable exploits."
        ),
        "steps": [14, 22, 23, 26, 27],
    },
    {
        "name": "SSH Analysis",
        "description": (
            "Specialized security assessment of SSH services. Evaluates SSH server configurations, "
            "cipher suites, key exchange algorithms, authentication methods, identifies security "
            "weaknesses in the implementation, and searches for potential exploits related to the "
            "SSH service version."
        ),
        "steps": [3, 34, 26, 27],
    },
    {
        "name": "SMB Analysis",
        "description": (
            "Specialized security assessment of SMB/CIFS services. Enumerates shared resources, "
            "user accounts, groups, and domain information, tests for anonymous access, identifies "
            "SMB protocol vulnerabilities, and searches for applicable exploits."
        ),
        "steps": [37, 26, 27, 35],
    },
    {
        "name": "OSINT",
        "description": (
            "Passive information gathering and reconnaissance activities. Collects publicly "
            "available information including email addresses, subdomains, and organizational data "
            "from various online sources without directly interacting with the target "
            "infrastructure, providing intelligence for further security assessments."
        ),
        "steps": [19, 30, 31, 46],
    },
    {
        "name": "Active Analysis",
        "description": (
            "Active security assessment that directly interacts with target systems. Performs port "
            "scanning, service enumeration, web application testing, vulnerability scanning, and "
            "exploit research."
        ),
        "steps": [38, 15, 21, 22, 23, 24, 25, 28, 32, 33, 34, 35, 26, 27, 39, 47, 48, 42],
    },
]


def create_default_processes(apps: Any, schema_editor: Any) -> None:
    """Create the processes that Rekono provides, with the steps that they run.

    The processes are matched by name, so the ones that a deployment already has are kept
    with the tasks that reference them, and the ones that its users removed stay removed.
    Each step is the identifier that tools/data/3_configurations.json gives to the tool
    configuration that it runs, so renaming a configuration doesn't reach this.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is created.
    """
    process_model = apps.get_model("processes", "Process")
    step_model = apps.get_model("processes", "Step")
    for process in DEFAULT_PROCESSES:
        entity, _ = process_model.objects.get_or_create(
            name=process["name"], defaults={"description": process["description"]}
        )
        for configuration in process["steps"]:
            step_model.objects.get_or_create(process=entity, configuration_id=configuration)


class Migration(migrations.Migration):

    # The steps reference the configurations, so the catalog has to be loaded first
    dependencies = [
        ('processes', '0003_initial'),
        ('tools', '0004_remove_argument_unique_argument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='step',
            name='unique step',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='step',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='step',
            name='tool',
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(max_length=500, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='description')]),
        ),
        migrations.AlterField(
            model_name='process',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.TextField(max_length=100, unique=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='name')]),
        ),
        migrations.AlterField(
            model_name='step',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tools.configuration'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('process', 'configuration'), name='unique_step'),
        ),
        migrations.RunPython(create_default_processes, migrations.RunPython.noop),
    ]
