# Generated by Django 5.2.16 on 2026-08-10 09:23

import django.db.models.deletion
import security.validators.enums
import security.validators.input_validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_initial'),
        ('tools', '0004_remove_argument_unique_argument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='step',
            name='unique step',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='step',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='step',
            name='tool',
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(max_length=500, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TEXT'], code='description')]),
        ),
        migrations.AlterField(
            model_name='process',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.TextField(max_length=100, unique=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='name')]),
        ),
        migrations.AlterField(
            model_name='step',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tools.configuration'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('process', 'configuration'), name='unique_step'),
        ),
    ]
