# Generated by Django 5.2.16 on 2026-08-10 09:23
# Touched: the removal of the version 1.x credential was moved after the _secret field that
# replaces it is added and the credential is copied into it

from typing import Any

import django.db.models.deletion
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models

from rekono.settings import CONFIG
from security.cryptography import Crypto


def _encrypt(value: str | None) -> str | None:
    """Encrypt a version 1.x secret the way that the version 2.x models store it.

    BaseEncrypted builds its encryptor from the configured key, and stores the value as
    plain text when there is none, so this does the same instead of using the models,
    whose historical versions have none of that behaviour.

    Returns:
        The encrypted secret, the plain one when no encryption key is configured, or None
        when there is no secret to migrate.
    """
    if not value:
        return None
    return Crypto(CONFIG.encryption_key).encrypt(value) if CONFIG.encryption_key else value


def _decrypt(value: str | None) -> str | None:
    """Recover a secret stored by the version 2.x models, as version 1.x kept it.

    Mirrors _encrypt, so a value that was stored as plain text because no encryption key
    was configured is returned untouched.

    Returns:
        The plain secret, or None when there is no secret to recover.
    """
    if not value:
        return None
    return Crypto(CONFIG.encryption_key).decrypt(value) if CONFIG.encryption_key else value


def migrate_1x_credentials(apps: Any, schema_editor: Any) -> None:
    """Copy the credentials of version 1.x into the field that encrypts them.

    Version 1.x stored the credential of an authentication as plain text, so it's encrypted
    here, since otherwise the authentications would keep their name and their type but lose
    the secret that makes them work.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    model = apps.get_model("authentications", "Authentication")
    for authentication in model.objects.exclude(credential__isnull=True).exclude(credential=""):
        authentication._secret = _encrypt(authentication.credential)
        authentication.save(update_fields=["_secret"])


def revert_1x_credentials(apps: Any, schema_editor: Any) -> None:
    """Put the secrets back as the plain text credentials that version 1.x expects.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    model = apps.get_model("authentications", "Authentication")
    for authentication in model.objects.exclude(_secret__isnull=True).exclude(_secret=""):
        authentication.credential = _decrypt(authentication._secret)
        authentication.save(update_fields=["credential"])


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
        ('target_ports', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='_secret',
            field=models.TextField(blank=True, db_column='secret', max_length=500, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['SECRET'], code='secret', deny_injections=True)]),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='name', deny_injections=True)]),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='target_port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authentication', to='target_ports.targetport'),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='type',
            field=models.TextField(choices=[('Basic', 'Basic'), ('Bearer', 'Bearer'), ('Cookie', 'Cookie'), ('Digest', 'Digest'), ('JWT', 'Jwt'), ('NTLM', 'Ntlm'), ('Token', 'Token')], max_length=8),
        ),
        migrations.RunPython(migrate_1x_credentials, revert_1x_credentials),
        migrations.RemoveField(
            model_name='authentication',
            name='credential',
        ),
    ]
