# Generated by Django 5.2.16 on 2026-08-10 09:23

import django.db.models.deletion
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
        ('target_ports', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='credential',
        ),
        migrations.AddField(
            model_name='authentication',
            name='_secret',
            field=models.TextField(blank=True, db_column='secret', max_length=500, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['SECRET'], code='secret', deny_injections=True)]),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='name', deny_injections=True)]),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='target_port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authentication', to='target_ports.targetport'),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='type',
            field=models.TextField(choices=[('Basic', 'Basic'), ('Bearer', 'Bearer'), ('Cookie', 'Cookie'), ('Digest', 'Digest'), ('JWT', 'Jwt'), ('NTLM', 'Ntlm'), ('Token', 'Token')], max_length=8),
        ),
    ]
