rootpath: null
frontend:
  url: https://127.0.0.1
security:
  # secret-key: 
  allowed-hosts:
    - 127.0.0.1
    - localhost
    - ::1
database:
  name: rekono
  # user:
  # password:
  host: 127.0.0.1
  port: 5432
rq:
  host: 127.0.0.1
  port: 6379
email:
  # host:
  # port:
  # user:
  # password:
  tls: true
tools:
  cmseek:
    directory: /usr/share/cmseek
  log4j-scan:
    directory: /opt/log4j-scan
  spring4shell-scan:
    directory: /opt/spring4shell-scan
  gittools:
    directory: /opt/GitTools