# Generated by Django 5.2.16 on 2026-08-10 09:25
# Touched: the targets migration it depends on was renamed to 0004_remove_targetport_target_and_more

import django.core.validators
import django.db.models.deletion
import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_remove_project_defectdojo_engagement_by_target_and_more'),
        ('targets', '0004_remove_targetport_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectDojoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.TextField(blank=True, max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET'])])),
                ('_api_token', models.TextField(blank=True, db_column='api_token', max_length=40, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['SECRET'], code='api_token')])),
                ('tls_validation', models.BooleanField(default=True)),
                ('tag', models.TextField(blank=True, max_length=200, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='tag')])),
                ('date_format', models.TextField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.CreateModel(
            name='DefectDojoSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('engagement_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('reimport', models.BooleanField(default=False)),
                ('close_old_findings', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defectdojo_sync', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.CreateModel(
            name='DefectDojoTargetSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('defectdojo_sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_syncs', to='defectdojo.defectdojosync')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defectdojo_sync', to='targets.target')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
    ]
