# Generated by Django 5.2.16 on 2026-08-10 09:25
# Touched: the DefectDojoSettings table is initialized with default DefectDojo settings and
# synchronizations from version 1.x are migrated to DefectDojoSync and DefectDojoTargetSync

from typing import Any

import django.core.validators
import django.db.models.deletion
import framework.logging
import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


def create_default_defectdojo_settings(apps: Any, schema_editor: Any) -> None:
    """Create the DefectDojo configuration, with no server until the users set one.

    The setup of a version 1.x deployment is copied over these defaults by
    settings.0002_settings, which runs afterwards, so an upgrade keeps the one that it had.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is created.
    """
    apps.get_model("defectdojo", "DefectDojoSettings").objects.get_or_create(
        pk=1,
        defaults={
            "server": None,
            "_api_token": None,
            "tls_validation": True,
            "tag": "rekono",
            "date_format": "%Y-%m-%d",
        },
    )


def migrate_1x_defectdojo_sync(apps: Any, schema_editor: Any) -> None:
    """Copy the DefectDojo synchronization of version 1.x into its new models.

    Version 1.x kept the synchronization in the project and the target, which version 2.x moved
    to their own models, so a project without synchronization gets no model at all.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    sync_model = apps.get_model("defectdojo", "DefectDojoSync")
    target_sync_model = apps.get_model("defectdojo", "DefectDojoTargetSync")
    for project in apps.get_model("projects", "Project").objects.filter(defectdojo_synchronization=True):
        sync, _ = sync_model.objects.get_or_create(
            project=project,
            defaults={
                "product_id": project.defectdojo_product_id,
                "engagement_id": None
                if project.defectdojo_engagement_by_target
                else project.defectdojo_engagement_id,
            },
        )
        if not project.defectdojo_engagement_by_target:
            continue
        for target in project.targets.filter(defectdojo_engagement_id__isnull=False):
            target_sync_model.objects.get_or_create(
                target=target,
                defaults={"defectdojo_sync": sync, "engagement_id": target.defectdojo_engagement_id},
            )


def revert_1x_defectdojo_sync(apps: Any, schema_editor: Any) -> None:
    """Put the synchronization back in the project and the target, as version 1.x kept it.

    A project whose targets each have their own engagement gets no engagement back, since
    version 2.x leaves that one empty and version 1.x ignored it anyway.

    Args:
        apps: Registry of the historical models, given by the migration framework.
        schema_editor: Not used, since only data is migrated.
    """
    project_model = apps.get_model("projects", "Project")
    target_model = apps.get_model("targets", "Target")
    for sync in apps.get_model("defectdojo", "DefectDojoSync").objects.all():
        project_model.objects.filter(pk=sync.project_id).update(
            defectdojo_synchronization=True,
            defectdojo_product_id=sync.product_id,
            defectdojo_engagement_id=sync.engagement_id,
            defectdojo_engagement_by_target=sync.engagement_id is None,
        )
    for target_sync in apps.get_model("defectdojo", "DefectDojoTargetSync").objects.all():
        target_model.objects.filter(pk=target_sync.target_id).update(
            defectdojo_engagement_id=target_sync.engagement_id
        )


class Migration(migrations.Migration):

    initial = True

    # Generated dependencies pointed at the migrations that drop the version 1.x DefectDojo columns,
    # so the sync models only need the ones that create their related models, letting this migration
    # copy that configuration before it's dropped
    dependencies = [
        ('projects', '0002_initial'),
        ('targets', '0003_prepare_targetport_move'),
    ]

    # The version 1.x columns are read before the migrations that drop them are applied
    run_before = [
        ('projects', '0003_remove_project_defectdojo_engagement_by_target_and_more'),
        ('targets', '0004_remove_targetport_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectDojoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.TextField(blank=True, max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['TARGET'])])),
                ('_api_token', models.TextField(blank=True, db_column='api_token', max_length=40, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['SECRET'], code='api_token')])),
                ('tls_validation', models.BooleanField(default=True)),
                ('tag', models.TextField(blank=True, max_length=200, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='tag')])),
                ('date_format', models.TextField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.CreateModel(
            name='DefectDojoSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('engagement_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('reimport', models.BooleanField(default=False)),
                ('close_old_findings', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defectdojo_sync', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.CreateModel(
            name='DefectDojoTargetSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('defectdojo_sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_syncs', to='defectdojo.defectdojosync')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defectdojo_sync', to='targets.target')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, framework.logging.LoggingEntity),
        ),
        migrations.RunPython(create_default_defectdojo_settings, migrations.RunPython.noop),
        migrations.RunPython(migrate_1x_defectdojo_sync, revert_1x_defectdojo_sync),
    ]
