from findings.enums import Severity
from findings.models import Credential, Technology, Vulnerability
from tests.cases import ToolTestCase
from tests.framework import ToolTest


class NucleiTest(ToolTest):
    tool_name = "Nuclei"
    cases = [
        ToolTestCase(
            "2022-dvwa.json",
            [
                {
                    "model": Technology,
                    "name": "PHP Detect",
                    "version": None,
                    "description": None,
                    "reference": None,
                },
                {
                    "model": Technology,
                    "name": "Apache/2.4.25 (Debian)",
                    "version": None,
                    "description": "Some Apache servers have the version on the response header. The OpenSSL version can be also obtained",
                    "reference": None,
                },
                {
                    "model": Technology,
                    "name": "php",
                    "version": None,
                    "description": "Wappalyzer Technology Detection",
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "robots.txt endpoint prober",
                    "description": None,
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: access-control-allow-headers",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "Redis Server - Unauthenticated Access",
                    "description": "Redis server without any required authentication was discovered.",
                    "severity": Severity.HIGH,
                    "cve": None,
                    "cwe": None,
                    "reference": "https://redis.io/topics/security",
                },
                {
                    "model": Vulnerability,
                    "name": "Exposed Gitignore",
                    "description": None,
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": "https://twitter.com/pratiky9967/status/1230001391701086208",
                },
                {
                    "model": Technology,
                    "name": "apachegeneric",
                    "version": None,
                    "description": "A web application firewall was detected.",
                    "reference": "https://github.com/ekultek/whatwaf",
                },
                {
                    "model": Vulnerability,
                    "name": "phpinfo Disclosure: 7.0.30",
                    "description": 'A "PHP Info" page was found. The output of the phpinfo() command can reveal detailed PHP environment information.',
                    "severity": Severity.LOW,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "README.md file disclosure",
                    "description": "Internal documentation file often used in projects which can contain sensitive information.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Credential,
                    "username": "admin",
                    "secret": "password",
                    "context": "DVWA Default Login",
                },
            ],
        ),
        ToolTestCase(
            "2025-dvwa.json",
            [
                {
                    "model": Credential,
                    "username": "admin",
                    "secret": "password",
                    "context": "DVWA Default Login",
                },
                {
                    "model": Vulnerability,
                    "name": "Cookies without Secure attribute - Detect",
                    "description": "Checks whether cookies in the HTTP response contain the Secure attribute. If the Secure flag is set, it means that the cookie can only be transmitted over HTTPS",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": "https://owasp.org/www-community/controls/SecureCookieAttribute",
                },
                {
                    "model": Technology,
                    "name": "apachegeneric",
                    "version": None,
                    "description": "A web application firewall was detected.",
                    "reference": "https://github.com/Ekultek/WhatWaf",
                },
                {
                    "model": Vulnerability,
                    "name": "README.md file disclosure",
                    "description": "Internal documentation file often used in projects which can contain sensitive information.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "robots.txt endpoint prober",
                    "description": None,
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Technology,
                    "name": "dvwa",
                    "version": None,
                    "description": "FingerprintHub Technology Fingerprint tests run in nuclei.",
                    "reference": "https://github.com/0x727/FingerprintHub",
                },
                {
                    "model": Technology,
                    "name": "php",
                    "version": None,
                    "description": "Wappalyzer Technology Detection",
                    "reference": None,
                },
                {
                    "model": Technology,
                    "name": "php",
                    "version": None,
                    "description": "Wappalyzer Technology Detection",
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: x-frame-options",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: x-content-type-options",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: x-permitted-cross-domain-policies",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: referrer-policy",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: clear-site-data",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: cross-origin-embedder-policy",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: cross-origin-opener-policy",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: cross-origin-resource-policy",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: strict-transport-security",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: content-security-policy",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "HTTP Missing Security Headers: permissions-policy",
                    "description": "This template searches for missing HTTP security headers. The impact of these missing headers can vary.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": None,
                    "reference": None,
                },
                {
                    "model": Vulnerability,
                    "name": "CAA Record",
                    "description": "A CAA record was discovered. A CAA record is used to specify which certificate authorities (CAs) are allowed to issue certificates for a domain.",
                    "severity": Severity.INFO,
                    "cve": None,
                    "cwe": "CWE-200",
                    "reference": "https://support.dnsimple.com/articles/caa-record/#whats-a-caa-record",
                },
            ],
        ),
    ]
