# Generated by Django 5.2.16 on 2026-08-10 09:23

import security.validators.enums
import security.validators.input_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_notification',
            new_name='email_notifications',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telegram_notification',
            new_name='telegram_notifications',
        ),
        migrations.AddField(
            model_name='user',
            name='_mfa_key',
            field=models.TextField(blank=True, db_column='mfa_key', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_scope',
            field=models.IntegerField(blank=True, choices=[(1, 'Invitation'), (2, 'Password Reset'), (3, 'Email Verification'), (4, 'Mfa')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='first_name')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='last_name')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_scope',
            field=models.TextField(choices=[('Only alerts', 'Only Alerts'), ('Only my executions', 'My Executions'), ('All executions', 'All Executions')], default='Only my executions', max_length=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True, validators=[security.validators.input_validator.FutureDatetimeValidator(code='otp_expiration')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, max_length=100, null=True, unique=True, validators=[security.validators.input_validator.Validator(security.validators.enums.Regex['NAME'], code='username')]),
        ),
    ]
