# Generated by Django 3.2.7 on 2021-12-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
