name: Check installation
on:
  workflow_dispatch:

env:
  RKN_USERNAME: rekono
  RKN_PASSWORD: rekono

jobs:
  docker-environment:
    name: Test default credentials
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Launch docker environment
        run: |
          docker-compose build
          docker-compose up -d

      - name: Test default credentials
        run: |
          RESPONSE=curl -LI https://127.0.0.1/api/token --data='{"username": "${RKN_USERNAME}", "password": "{$RKN_PASSWORD}"' -o /dev/null -w '%{http_code}\n' -s
          if [ RESPONSE != 200]; then exit 10; fi