name: Backend style
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/backend/**'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Flake8 check
        uses: valentijnscholten/flake8-your-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mypy:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Install MyPy
        run: python3 -m pip install mypy==0.931
      
      - name: MyPy check
        run: mypy --namespace-packages --package rekono --install-types --non-interactive
