name: Frontend style
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/frontend/**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install ESLint
        working-directory: src/frontend
        run: |
          npm install .
          npm install -g eslint
      
      - name: ESLint check
        run: eslint src/frontend/ --ext .js,.jsx,.ts,.tsx
