name: Code style
on:
  workflow_dispatch:
  pull_request:

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Check changed files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**'

      - name: Checkout
        if: ${{ steps.changes.outputs.backend == 'true' || github.event_name != 'pull_request' }}
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0

      - name: Install UV
        if: ${{ steps.changes.outputs.backend == 'true' || github.event_name != 'pull_request' }}
        uses: astral-sh/setup-uv@cb84d12dc6a0d495b82fcae14fa4559b90698660
        with:
          activate-environment: true
          python-version: 3.12.0 # Required by pytype

      - name: Install dependencies
        working-directory: backend
        if: ${{ steps.changes.outputs.backend == 'true' || github.event_name != 'pull_request' }}
        run: uv sync --locked

      - name: Ruff
        if: ${{ steps.changes.outputs.backend == 'true' || github.event_name != 'pull_request' }}
        working-directory: backend
        run: |
          uvx ruff format --check
          uvx ruff check

      - name: Flake8
        if: ${{ (steps.changes.outputs.backend == 'true' || github.event_name != 'pull_request') && !cancelled() }}
        working-directory: backend
        run: uvx flake8 .

      - name: PyType
        if: ${{ (steps.changes.outputs.backend == 'true' || github.event_name != 'pull_request') && !cancelled() }}
        working-directory: backend
        run: uvx pytype --disable "import-error,pyi-error,invalid-annotation" --keep-going --jobs 100 .

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check changed files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'

      - name: Checkout
        if: ${{ steps.changes.outputs.frontend == 'true' || github.event_name != 'pull_request' }}
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@6e7bdbda5fe05107efc88b23b7ed00aa05f84ca0
        with:
          version: 10.33.0

      - name: Install Node dependencies
        if: ${{ steps.changes.outputs.frontend == 'true' || github.event_name != 'pull_request' }}
        working-directory: frontend
        run: |
          pnpm install . --ignore-scripts
          ls -la
          ls -la .nuxt/ | grep eslint

      - name: ESLint
        if: ${{ steps.changes.outputs.frontend == 'true' || github.event_name != 'pull_request' }}
        working-directory: frontend/
        run: |
          ls -la
          ls -la .nuxt/ | grep eslint
          pnpm run eslint

      - name: Prettier
        if: ${{ (steps.changes.outputs.frontend == 'true' || github.event_name != 'pull_request') && !cancelled() }}
        working-directory: frontend/
        run: pnpm run prettier
