name: Backend style
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/backend/**'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r src/backend/requirements-dev.txt
      
      - name: Black check
        run: python -m black --check src/backend/

  mypy:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r src/backend/requirements-dev.txt
      
      - name: MyPy check
        run: mypy --namespace-packages --package rekono --install-types --non-interactive
