name: Containers
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docker/**'
      - 'docker-compose.yml'
  release:
    types: [published]

jobs:
  docker-images:
    runs-on: ubuntu-latest
    environment: docker-hub
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Backend
            dockerfile: docker/Dockerfile
            image: rekono-backend
            target: backend
          - name: Frontend
            dockerfile: docker/Dockerfile
            image: rekono-frontend
            target: frontend
          - name: Nginx
            dockerfile: docker/nginx/Dockerfile
            image: rekono-nginx
            target: null
          - name: Worker
            dockerfile: docker/Dockerfile
            image: rekono-worker
            target: worker
            # Docker image is very large and we need some extra GB to complete the build
            clean-disk: true
    name: ${{ matrix.name }}
    defaults:
      run:
        shell: bash
        working-directory: /mnt
    steps:
      - name: Free disk space
        if: ${{ matrix.clean-disk == true }}
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: true
      
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-docker-action@5223f80f64587ec3bf588369be41ea8e6cda1dbb
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Login to Docker Hub
        uses: docker/login-action@36864503dc2a3702db7dc554479e3e1a29bb8337
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@76c0984808678992dc9f24265d45acf8c8fc8a96

      - name: Get metadata
        id: metadata
        working-directory: backend/rekono
        run: |
          REKONO_VERSION=$(grep -oP '^VERSION = "\K[^"]+' settings.py | head -1)
          echo "version=$REKONO_VERSION" >> "$GITHUB_OUTPUT"
          echo "date=$(date --rfc-3339=seconds)" >> "$GITHUB_OUTPUT"

      - name: Build and push unstable
        if: ${{ github.event_name != 'release' }}
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          file: ${{ matrix.dockerfile }}
          target: ${{ matrix.target }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USER }}/${{ matrix.image }}:unstable
          load: true
          push: true
          sbom: true
          provenance: true
          build-args: |
            LABEL_CREATED=${{ steps.metadata.outputs.date }}
            LABEL_VERSION=${{ steps.metadata.outputs.version }}-dev
            LABEL_REVISION=${{ github.sha }}
      
      - name: Build and push release
        if: ${{ github.event_name == 'release' }}
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          file: ${{ matrix.dockerfile }}
          target: ${{ matrix.target }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USER }}/${{ matrix.image }}:${{ github.event.release.name }},${{ secrets.DOCKER_USER }}/${{ matrix.image }}:latest,${{ secrets.DOCKER_USER }}/${{ matrix.image }}:unstable
          load: true
          push: true
          sbom: true
          provenance: true
          build-args: |
            LABEL_CREATED=${{ steps.metadata.outputs.date }}
            LABEL_VERSION=${{ github.event.release.name }}
            LABEL_REVISION=${{ github.sha }}

      - name: Trivy
        uses: aquasecurity/trivy-action@bfa4b33a029b9aa80ddb784b45574c30e072c59e
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/${{ matrix.image }}:unstable
          format: table
          exit-code: 0
      
      - name: Dockle
        uses: goodwithtech/dockle-action@e30e6af832aad6ea7dca2a248d31a85eab6dbd68
        with:
          image: ${{ secrets.DOCKER_USER }}/${{ matrix.image }}:unstable
          format: json
          output: ${{ matrix.name }}-dockle.json
          exit-code: 0
          exit-level: warn
      
      - name: Upload Dockle report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}-dockle.json
          if-no-files-found: warn

  kali-release:
    name: Kali Release
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    environment: gitlab
    needs: docker-images
    steps:
      - name: Checkout GitLab repository
        run: git clone https://gitlab.com/pablosnt/rekono.git rekono-kbx

      - name: Update debian/changelog
        working-directory: rekono-kbx/debian
        shell: python
        run: |
          import pytz
          from datetime import datetime
          with open('changelog', 'r') as changelog:
            old_changes = changelog.read()
          tz = pytz.timezone('Europe/Madrid')
          d = tz.localize(datetime.now())
          change_time = d.strftime('%a, %d %b %Y %H:%M:%S %z')
          new_changes = f'rekono-kbx (${{ github.event.release.name }}) kali-dev; urgency=medium\n\n  * Update Rekono version to ${{ github.event.release.name }}.\n\n -- Pablo Santiago López <${{ secrets.GITLAB_EMAIL }}>  {change_time}\n\n'
          with open('changelog', 'w') as changelog:
            changelog.write(new_changes + old_changes)
      
      - name: Commit changes to GitLab
        working-directory: rekono-kbx
        run: |
          git config user.name 'Pablo Santiago'
          git config user.email '${{ secrets.GITLAB_EMAIL }}'
          git checkout -b release/${{ github.event.release.name }}
          git add .
          git commit -m "Update Rekono version to ${{ github.event.release.name }}"
          git config credential.helper '!f() { sleep 1; echo "username=${{ secrets.GITLAB_USER }}"; echo "password=${{ secrets.GITLAB_TOKEN }}"; }; f'
          git push --set-upstream origin release/${{ github.event.release.name }}
      
      - name: GitLab merge request
        shell: python
        env:
          GITLAB_PROJECT_ID: 45783845
        run: |
          import requests
          headers = {
            'PRIVATE-TOKEN': '${{ secrets.GITLAB_TOKEN }}'
          }
          data = {
            'title': 'Update Rekono version to ${{ github.event.release.name }}',
            'source_branch': 'release/${{ github.event.release.name }}',
            'target_branch': 'kali/master',
          }
          response = requests.post('https://gitlab.com/api/v4/projects/${{ env.GITLAB_PROJECT_ID }}/merge_requests', data=data, headers=headers)
          if response.status_code != 201:
            print(response.text)
          response.raise_for_status()

      - name: GitLab issue in Kali Linux repository
        shell: python
        env:
          GITLAB_PROJECT_ID: 48406619
        run: |
          import requests
          headers = {
            'PRIVATE-TOKEN': '${{ secrets.GITLAB_TOKEN }}'
          }
          data = {
            'title': 'New Rekono version ${{ github.event.release.name }}',
            'description': '''Please, upgrade the `rekono-kbx` Kali Linux package to the latest version `${{ github.event.release.name }}`.

            New version details:
            - [GitHub release](https://github.com/pablosnt/rekono/releases/tag/${{ github.event.release.name }})
            - [Rekono changelog](https://github.com/pablosnt/rekono/blob/main/CHANGELOG.md)

            Thank you very much!
            ''',
          }
          response = requests.post('https://gitlab.com/api/v4/projects/${{ env.GITLAB_PROJECT_ID }}/issues', data=data, headers=headers)
          response.raise_for_status()
