name: SAST
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.166.0-nonroot@sha256:3b34104fa0eac1940fd96a2e18d2fb0fe7615dbd93a6d59e7d2c10e4cddcea1a
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      
      - name: Semgrep
        run: semgrep scan --config=auto --error --json -o semgrep.json .
      
      - name: Upload report as GitHub artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: Semgrep
          path: semgrep.json
          if-no-files-found: warn

  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@a687b25bf3aa149153e80ed5f45292e47589888c
        with:
          advanced-security: false
