name: Secrets
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  gitleaks:
    name: GitLeaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: GitLeaks
        uses: gitleaks/gitleaks-action@961680e5305a30eb575f3ddf6bb6b2e265b68f0a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_ENABLE_SUMMARY: false
  
  trufflehog:
    name: TruffleHog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: TruffleHog
      uses: trufflesecurity/trufflehog@ac0805e53b065e7188181fc80dce1800dfa51ab9
      with:
        extra_args: --results=verified,unknown