name: Secrets
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  gitleaks:
    name: GitLeaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: GitLeaks
        uses: gitleaks/gitleaks-action@9c66aa96d2700e2b6aa0f9f7021ae6e5cc7a4375
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_ENABLE_SUMMARY: false
  
  trufflehog:
    name: TruffleHog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      with:
        persist-credentials: false

    - name: TruffleHog
      uses: trufflesecurity/trufflehog@afda467cf4dc2fb559c548306a8280d6743f8537
      with:
        extra_args: --results=verified,unknown